project_id = "stcpycushiccfvrqwipw"

[functions.signup-with-approval]
verify_jwt = false

[functions.login-with-audit]
verify_jwt = false

[functions.send-to-committee]
verify_jwt = false

[functions.submit-vote]
verify_jwt = false

[functions.convert-incident]
verify_jwt = false

[functions.admin-set-password]
verify_jwt = false

[functions.user-update-password]
verify_jwt = false
