project_id = "stcpycushiccfvrqwipw"

[functions.signup-with-approval]
verify_jwt = false

[functions.login-with-audit]
verify_jwt = false

[functions.send-to-committee]
verify_jwt = false

[functions.submit-vote]
verify_jwt = false

[functions.convert-incident]
verify_jwt = false

[functions.admin-set-password]
verify_jwt = false

[functions.user-update-password]
verify_jwt = false

[functions.efd-parse-document]
verify_jwt = false

[functions.efd-generate-epics]
verify_jwt = false

[functions.efd-generate-features]
verify_jwt = false

[functions.efd-extract-text]
verify_jwt = false

[functions.jira-api]
verify_jwt = false

[functions.injira-import-analyzer]
verify_jwt = false

[functions.injira-defect-triage]
verify_jwt = false

[functions.injira-import]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.ai-traceability-gaps]
verify_jwt = false

[functions.ai-fail-to-defect]
verify_jwt = false

[functions.ai-test-recommendations]
verify_jwt = false

[functions.ai-narrative-report]
verify_jwt = false

[functions.ai-assist-compliance]
verify_jwt = false

[functions.ai-assist-publish]
verify_jwt = false

[functions.ai-assist-upload]
verify_jwt = false

[functions.ai-assist-summary]
verify_jwt = false

[functions.ai-assist-analyze]
verify_jwt = false

[functions.capacity-ai]
verify_jwt = false
