/**
 * notionImportService — Real wiring to notion-fetch edge function + ph_work_items insert.
 * Guards: item_key auto-generated by trigger, no deleted_at on insert, no hard delete.
 */
import { supabase } from '@/integrations/supabase/client';
import type { NotionFetchResponse, NotionRow, NotionImportMapping, PhWorkItemInsert } from '@/types/notionImport';

export async function fetchNotionDatabase(
  integrationToken: string,
  databaseUrl: string
): Promise<NotionFetchResponse> {
  const { data, error } = await supabase.functions.invoke('notion-fetch', {
    body: { integrationToken, databaseUrl },
  });
  if (error) throw new Error(error.message);
  const res = data as NotionFetchResponse;
  if (!res.success) throw new Error(res.error || 'Unknown error from Notion');
  return res;
}

export async function importNotionRows(params: {
  rows: NotionRow[];
  mappings: Record<string, string>;
  projectId: string;
  defaultItemType: string;
  onProgress?: (done: number) => void;
}): Promise<{ imported: number; skipped: number; failed: number }> {
  const { rows, mappings, projectId, defaultItemType, onProgress } = params;
  let imported = 0, skipped = 0, failed = 0;

  // Check which Notion page IDs already exist
  const notionIds = rows.map(r => r.notionPageId);
  const existingIds = new Set<string>();

  // Batch the existence check (in_ has limits)
  for (let i = 0; i < notionIds.length; i += 200) {
    const batch = notionIds.slice(i, i + 200);
    const { data: existing } = await supabase
      .from('ph_work_items')
      .select('jira_issue_id')
      .in('jira_issue_id', batch)
      .is('deleted_at', null);
    (existing || []).forEach(r => { if (r.jira_issue_id) existingIds.add(r.jira_issue_id); });
  }

  // Build active mappings (skip __skip__)
  const activeMappings = Object.entries(mappings).filter(([, v]) => v !== '__skip__');

  // Build insert batch
  const toInsert: Record<string, any>[] = [];
  for (const row of rows) {
    if (existingIds.has(row.notionPageId)) { skipped++; continue; }

    const record: Record<string, any> = {
      project_id: projectId,
      item_type: defaultItemType,
      status: 'To Do',
      sync_source: 'notion',
      jira_issue_id: row.notionPageId,
      jira_url: row.notionPageUrl,
      // item_key: auto-generated by trg_item_key — NEVER set manually
      // deleted_at: NEVER set on insert
    };

    for (const [notionProp, catalystCol] of activeMappings) {
      const val = row.properties[notionProp];
      if (val !== null && val !== undefined) {
        record[catalystCol] = val;
      }
    }

    // summary is required by the table
    if (!record.summary) record.summary = 'Untitled';

    toInsert.push(record);
  }

  // Rows with no summary that were filtered out
  const noSummaryCount = rows.length - skipped - toInsert.length;
  failed += noSummaryCount;

  // Batch insert in chunks of 50
  for (let i = 0; i < toInsert.length; i += 50) {
    const chunk = toInsert.slice(i, i + 50);

    // @ts-ignore — dynamic column set
    const { error } = await supabase.from('ph_work_items').insert(chunk as any[]);

    if (error) {
      console.error('[notion-import] batch error:', error.message);
      failed += chunk.length;
    } else {
      imported += chunk.length;
    }

    onProgress?.(skipped + imported + failed);
  }

  // Log to activity_logs
  await supabase.from('activity_logs').insert({
    entity_type: 'notion_import',
    entity_id: crypto.randomUUID(),
    action: 'bulk_import',
    after_json: { imported, skipped, failed, projectId, source: 'notion' } as any,
  });

  return { imported, skipped, failed };
}
