/**
 * WorkItem CRUD Service — Interfaces with ph_work_items and related tables
 */
import { supabase } from '@/integrations/supabase/client';
import { enqueueWorkItemOperation } from '@/lib/jira-writeback';

export interface CreateWorkItemInput {
  project_id: string;
  type_id: string;
  status_id: string;
  title: string;
  item_type: string;
  description?: any;
  priority?: string;
  assignee_id?: string | null;
  parent_id?: string | null;
  due_date?: string | null;
  start_date?: string | null;
  release_id?: string | null;
  department?: string | null;
  team?: string | null;
  environment?: string | null;
  security_level?: string;
  is_flagged?: boolean;
  flag_reason?: string | null;
  label_ids?: string[];
}

export interface UpdateWorkItemInput {
  title?: string;
  summary?: string;
  description?: any;
  status_id?: string;
  type_id?: string;
  priority?: string;
  assignee_id?: string | null;
  parent_id?: string | null;
  due_date?: string | null;
  start_date?: string | null;
  release_id?: string | null;
  department?: string | null;
  team?: string | null;
  environment?: string | null;
  security_level?: string;
  is_flagged?: boolean;
  flag_reason?: string | null;
  resolution?: string | null;
}

// ─── CREATE ────────────────────────────────────────────────
export async function createWorkItem(input: CreateWorkItemInput) {
  const { label_ids, ...insertData } = input;

  // item_key and sequence_num are auto-generated by ph_generate_item_key trigger
  // We need to supply dummy values that the trigger will overwrite
  const { data: seqData } = await supabase
    .from('ph_work_items')
    .select('sequence_num')
    .eq('project_id', input.project_id)
    .order('sequence_num', { ascending: false })
    .limit(1);

  const nextSeq = ((seqData?.[0]?.sequence_num as number) || 0) + 1;

  const { data: proj } = await supabase
    .from('ph_projects')
    .select('key')
    .eq('id', input.project_id)
    .single();

  const itemKey = `${proj?.key || 'PROJ'}-${nextSeq}`;

  const { data, error } = await supabase
    .from('ph_work_items')
    .insert({
      ...insertData,
      item_key: itemKey,
      sequence_num: nextSeq,
      summary: input.title,
      sort_order: 0,
      priority: input.priority || 'medium',
      security_level: input.security_level || 'standard',
      is_flagged: input.is_flagged || false,
    })
    .select('id, item_key, title, summary')
    .single();

  if (error) throw new Error(error.message);

  // Attach labels if provided
  if (label_ids && label_ids.length > 0 && data) {
    await supabase.from('ph_work_item_labels').insert(
      label_ids.map(lid => ({ work_item_id: data.id, label_id: lid }))
    );
  }

  // ── Jira write-back enqueue (non-blocking) ──
  try {
    const { data: connection } = await supabase
      .from('jira_connections')
      .select('id')
      .eq('is_active', true)
      .maybeSingle();

    if (connection && data) {
      const { data: mapping } = await (supabase
        .from('jira_project_mappings') as any)
        .select('jira_project_key')
        .eq('catalyst_project_id', input.project_id)
        .eq('sync_enabled', true)
        .maybeSingle();

      const payload = {
        title: input.title,
        description: input.description ?? '',
        priority: input.priority ?? 'medium',
        assignee_account_id: null,
        project_key: mapping?.jira_project_key ?? null,
      };

      await enqueueWorkItemOperation({
        phWorkItemId: data.id,
        operation: 'create',
        operationPayload: payload,
      });

      await (supabase
        .from('ph_work_items') as any)
        .update({ jira_sync_status: 'pending' } as any)
        .eq('id', data.id);
    }
  } catch (jiraErr) {
    console.error('Jira write-back enqueue failed:', jiraErr);
  }

  return data;
}

// ─── GET (with full joins) ─────────────────────────────────
export async function getWorkItem(id: string) {
  const { data, error } = await supabase
    .from('ph_work_items')
    .select(`
      *,
      ph_work_types!ph_work_items_type_id_fkey (id, name, color, icon, level),
      ph_workflow_statuses!ph_work_items_status_id_fkey (id, name, category, color)
    `)
    .eq('id', id)
    .single();

  if (error) throw new Error(error.message);

  // Fetch assignee + reporter profiles
  const profileIds = [data?.assignee_id, data?.reporter_id].filter(Boolean);
  if (profileIds.length > 0) {
    const { data: profiles } = await supabase
      .from('profiles')
      .select('id, full_name, avatar_url')
      .in('id', profileIds);
    const pMap = new Map((profiles || []).map(p => [p.id, p]));
    (data as any).assignee_profile = pMap.get(data.assignee_id) || null;
    (data as any).reporter_profile = pMap.get(data.reporter_id) || null;
  }

  // Fetch labels
  const { data: labelLinks } = await supabase
    .from('ph_work_item_labels')
    .select('label_id, ph_labels(id, name, color)')
    .eq('work_item_id', id);
  (data as any).labels = (labelLinks || []).map((l: any) => l.ph_labels).filter(Boolean);

  // Fetch children
  const { data: children } = await supabase
    .from('ph_work_items')
    .select('id, item_key, title, summary, priority, status_id, ph_workflow_statuses!ph_work_items_status_id_fkey(name, category, color)')
    .eq('parent_id', id)
    .order('sort_order');
  (data as any).children = children || [];

  // Fetch parent
  if (data?.parent_id) {
    const { data: parent } = await supabase
      .from('ph_work_items')
      .select('id, item_key, title, summary')
      .eq('id', data.parent_id)
      .single();
    (data as any).parent = parent;
  }

  // Fetch release
  if (data?.release_id) {
    const { data: release } = await supabase
      .from('ph_releases')
      .select('id, name, status, release_date')
      .eq('id', data.release_id)
      .single();
    (data as any).release = release;
  }

  return data;
}

// ─── UPDATE (with activity logging) ────────────────────────
export async function updateWorkItem(
  id: string,
  changes: UpdateWorkItemInput,
  userId?: string
) {
  // Fetch current values for audit logging
  const { data: current } = await supabase
    .from('ph_work_items')
    .select('*')
    .eq('id', id)
    .single();

  if (!current) throw new Error('Work item not found');

  const { data, error } = await supabase
    .from('ph_work_items')
    .update(changes)
    .eq('id', id)
    .select('id, item_key')
    .single();

  if (error) throw new Error(error.message);

  // Auto-resolve userId if not provided
  let actorId = userId;
  if (!actorId) {
    const { data: { user } } = await supabase.auth.getUser();
    actorId = user?.id ?? undefined;
  }

  // Log each changed field to activity log
  if (actorId) {
    const logs: any[] = [];
    for (const [key, newVal] of Object.entries(changes)) {
      const oldVal = (current as any)[key];
      if (String(oldVal) !== String(newVal)) {
        logs.push({
          work_item_id: id,
          user_id: actorId,
          action: 'updated',
          field_name: key,
          old_value: oldVal != null ? String(oldVal) : null,
          new_value: newVal != null ? String(newVal) : null,
        });
      }
    }
    if (logs.length > 0) {
      await supabase.from('ph_activity_log').insert(logs);
    }
  }

  // ── Jira write-back enqueue (non-blocking) ──
  try {
    const { data: item } = await supabase
      .from('ph_work_items')
      .select('id, jira_key, jira_sync_status')
      .eq('id', id)
      .maybeSingle() as any;

    const { data: connection } = await supabase
      .from('jira_connections')
      .select('id')
      .eq('is_active', true)
      .maybeSingle();

    if (connection && item?.jira_key) {
      const payload: Record<string, any> = {};
      if (changes.title !== undefined) payload.title = changes.title;
      if (changes.description !== undefined) payload.description = changes.description;
      if (changes.priority !== undefined) payload.priority = changes.priority;
      if (changes.status_id !== undefined) payload.status_id = changes.status_id;
      if (changes.assignee_id !== undefined) payload.assignee_id = changes.assignee_id;
      payload.jira_key = item.jira_key;

      await enqueueWorkItemOperation({
        phWorkItemId: id,
        operation: 'update',
        operationPayload: payload,
      });

      await (supabase
        .from('ph_work_items') as any)
        .update({ jira_sync_status: 'pending' })
        .eq('id', id);
    }
  } catch (jiraErr) {
    console.error('Jira update enqueue failed:', jiraErr);
  }

  return data;
}

// ─── DELETE ────────────────────────────────────────────────
export async function deleteWorkItem(id: string) {
  // ── Jira write-back enqueue BEFORE delete (non-blocking) ──
  try {
    const { data: item } = await supabase
      .from('ph_work_items')
      .select('id, jira_key')
      .eq('id', id)
      .maybeSingle() as any;

    const { data: connection } = await supabase
      .from('jira_connections')
      .select('id')
      .eq('is_active', true)
      .maybeSingle();

    if (connection && item?.jira_key) {
      await enqueueWorkItemOperation({
        phWorkItemId: id,
        operation: 'delete',
        operationPayload: { jira_key: item.jira_key },
      });
    }
  } catch (jiraErr) {
    console.error('Jira delete enqueue failed:', jiraErr);
  }

  const { error } = await supabase
    .from('ph_work_items')
    .delete()
    .eq('id', id);

  if (error) throw new Error(error.message);
}

// ─── LIST (paginated) ──────────────────────────────────────
export async function listWorkItems(
  projectId: string,
  options?: {
    page?: number;
    pageSize?: number;
    sortBy?: string;
    sortDir?: 'asc' | 'desc';
    filters?: Record<string, any>;
  }
) {
  const { page = 0, pageSize = 50, sortBy = 'sort_order', sortDir = 'asc', filters } = options || {};

  let query = supabase
    .from('ph_work_items')
    .select(`
      *,
      ph_work_types!ph_work_items_type_id_fkey (id, name, color, icon, level),
      ph_workflow_statuses!ph_work_items_status_id_fkey (id, name, category, color)
    `, { count: 'exact' })
    .eq('project_id', projectId)
    .order(sortBy, { ascending: sortDir === 'asc' })
    .range(page * pageSize, (page + 1) * pageSize - 1);

  // Apply filters
  if (filters?.status_id) query = query.eq('status_id', filters.status_id);
  if (filters?.priority) query = query.eq('priority', filters.priority);
  if (filters?.assignee_id) query = query.eq('assignee_id', filters.assignee_id);
  if (filters?.type_id) query = query.eq('type_id', filters.type_id);

  const { data, error, count } = await query;

  if (error) throw new Error(error.message);
  return { items: data || [], total: count || 0, page, pageSize };
}
