/**
 * Programmatic mirror of tokens.css.
 * Use `token("color.text.subtle")` for JS consumers (charts, inline styles, motion libs).
 *
 * Values are CSS custom property *references*, so they respect the current theme.
 */

const t = (name: string) => `var(--ds-${name})`;

export const tokens = {
  color: {
    background: {
      input: t("color-background-input"),
      inputHovered: t("color-background-input-hovered"),
      inputPressed: t("color-background-input-pressed"),
      neutral: t("color-background-neutral"),
      neutralSubtle: t("color-background-neutral-subtle"),
      neutralSubtleHovered: t("color-background-neutral-subtle-hovered"),
      neutralSubtlePressed: t("color-background-neutral-subtle-pressed"),
      neutralHovered: t("color-background-neutral-hovered"),
      neutralPressed: t("color-background-neutral-pressed"),
      neutralBold: t("color-background-neutral-bold"),
      neutralBoldHovered: t("color-background-neutral-bold-hovered"),
      selected: t("color-background-selected"),
      selectedHovered: t("color-background-selected-hovered"),
      selectedPressed: t("color-background-selected-pressed"),
      disabled: t("color-background-disabled"),
      accent: {
        blue: {
          subtlest: t("color-background-accent-blue-subtlest"),
          subtler: t("color-background-accent-blue-subtler"),
          subtle: t("color-background-accent-blue-subtle"),
          bolder: t("color-background-accent-blue-bolder"),
        },
        teal: {
          subtlest: t("color-background-accent-teal-subtlest"),
          subtler: t("color-background-accent-teal-subtler"),
          bolder: t("color-background-accent-teal-bolder"),
        },
        purple: {
          subtlest: t("color-background-accent-purple-subtlest"),
          subtler: t("color-background-accent-purple-subtler"),
          bolder: t("color-background-accent-purple-bolder"),
        },
      },
      information: t("color-background-information"),
      informationHovered: t("color-background-information-hovered"),
      informationPressed: t("color-background-information-pressed"),
      informationBold: t("color-background-information-bold"),
      success: t("color-background-success"),
      successHovered: t("color-background-success-hovered"),
      successPressed: t("color-background-success-pressed"),
      successBold: t("color-background-success-bold"),
      warning: t("color-background-warning"),
      warningHovered: t("color-background-warning-hovered"),
      warningPressed: t("color-background-warning-pressed"),
      warningBold: t("color-background-warning-bold"),
      danger: t("color-background-danger"),
      dangerHovered: t("color-background-danger-hovered"),
      dangerPressed: t("color-background-danger-pressed"),
      dangerBold: t("color-background-danger-bold"),
      discovery: t("color-background-discovery"),
      discoveryBold: t("color-background-discovery-bold"),
    },
    text: {
      DEFAULT: t("color-text"),
      subtle: t("color-text-subtle"),
      subtlest: t("color-text-subtlest"),
      disabled: t("color-text-disabled"),
      inverse: t("color-text-inverse"),
      brand: t("color-text-brand"),
      selected: t("color-text-selected"),
      information: t("color-text-information"),
      success: t("color-text-success"),
      warning: t("color-text-warning"),
      danger: t("color-text-danger"),
      discovery: t("color-text-discovery"),
      accent: {
        blue: t("color-text-accent-blue"),
        teal: t("color-text-accent-teal"),
        purple: t("color-text-accent-purple"),
      },
    },
    link: {
      DEFAULT: t("color-link"),
      hovered: t("color-link-hovered"),
      pressed: t("color-link-pressed"),
      visited: t("color-link-visited"),
    },
    icon: {
      DEFAULT: t("color-icon"),
      subtle: t("color-icon-subtle"),
      disabled: t("color-icon-disabled"),
      inverse: t("color-icon-inverse"),
      brand: t("color-icon-brand"),
      information: t("color-icon-information"),
      success: t("color-icon-success"),
      warning: t("color-icon-warning"),
      danger: t("color-icon-danger"),
      discovery: t("color-icon-discovery"),
    },
    border: {
      DEFAULT: t("color-border"),
      bold: t("color-border-bold"),
      subtle: t("color-border-subtle"),
      disabled: t("color-border-disabled"),
      inverse: t("color-border-inverse"),
      focused: t("color-border-focused"),
      selected: t("color-border-selected"),
      input: t("color-border-input"),
      brand: t("color-border-brand"),
      information: t("color-border-information"),
      success: t("color-border-success"),
      warning: t("color-border-warning"),
      danger: t("color-border-danger"),
      discovery: t("color-border-discovery"),
    },
  },
  elevation: {
    surface: {
      DEFAULT: t("elevation-surface"),
      sunken: t("elevation-surface-sunken"),
      raised: t("elevation-surface-raised"),
      overlay: t("elevation-surface-overlay"),
    },
    shadow: {
      raised: t("elevation-shadow-raised"),
      overflow: t("elevation-shadow-overflow"),
      overlay: t("elevation-shadow-overlay"),
    },
  },
  space: {
    0: t("space-0"),
    "025": t("space-025"),
    "050": t("space-050"),
    "075": t("space-075"),
    100: t("space-100"),
    150: t("space-150"),
    200: t("space-200"),
    250: t("space-250"),
    300: t("space-300"),
    400: t("space-400"),
    500: t("space-500"),
    600: t("space-600"),
    800: t("space-800"),
    1000: t("space-1000"),
  },
  radius: {
    0: t("radius-0"),
    100: t("radius-100"),
    200: t("radius-200"),
    300: t("radius-300"),
    400: t("radius-400"),
    round: t("radius-round"),
  },
  font: {
    family: {
      body: t("font-family-body"),
      heading: t("font-family-heading"),
      monospace: t("font-family-monospace"),
    },
    size: {
      "075": t("font-size-075"),
      100: t("font-size-100"),
      200: t("font-size-200"),
      300: t("font-size-300"),
      400: t("font-size-400"),
      500: t("font-size-500"),
      600: t("font-size-600"),
      700: t("font-size-700"),
      800: t("font-size-800"),
    },
    weight: {
      regular: t("font-weight-regular"),
      medium: t("font-weight-medium"),
      semibold: t("font-weight-semibold"),
      bold: t("font-weight-bold"),
    },
    lineHeight: {
      100: t("line-height-100"),
      200: t("line-height-200"),
      300: t("line-height-300"),
      400: t("line-height-400"),
      500: t("line-height-500"),
      600: t("line-height-600"),
    },
  },
  motion: {
    duration: {
      small: t("motion-duration-small"),
      medium: t("motion-duration-medium"),
      large: t("motion-duration-large"),
    },
    ease: {
      out: t("motion-ease-out"),
      inOut: t("motion-ease-in-out"),
    },
  },
} as const;

export type Tokens = typeof tokens;
