/**
 * ═══════════════════════════════════════════════════════════════════
 * CATALYST NOTIFICATION EVENTS REGISTRY
 * Master catalog of all notification trigger events across all hubs.
 * Benchmarked against Atlassian Jira notification schemes.
 *
 * Total: 198 trigger events across 9 hubs + cross-hub operations.
 *
 * Priority Levels:
 *   P1 (Critical) — Approvals, SLA breaches, escalations
 *   P2 (High)     — Assignments, mentions, blockers
 *   P3 (Medium)   — Status changes, comments on owned items
 *   P4 (Low)      — Watching updates, bulk changes, archive events
 *
 * Last updated: 2026-04-06
 * ═══════════════════════════════════════════════════════════════════
 */

// ── Hub Sources ─────────────────────────────────────────────────
export type HubSource =
  | 'StrategyHub'
  | 'ProductHub'
  | 'ProjectHub'
  | 'ReleaseHub'
  | 'TestHub'
  | 'IncidentHub'
  | 'TaskHub'
  | 'PlanHub'
  | 'WikiHub'
  | 'CrossHub';

// ── Trigger Categories ──────────────────────────────────────────
export type TriggerCategory =
  | 'assignments'
  | 'status_changes'
  | 'comments_mentions'
  | 'approvals_signoffs'
  | 'incidents_sla'
  | 'testing'
  | 'strategy_okrs'
  | 'documents_wiki'
  | 'dependencies_links'
  | 'system_ai'
  | 'releases'
  | 'planning'
  | 'product_ideas';

// ── Priority ────────────────────────────────────────────────────
export type TriggerPriority = 'P1' | 'P2' | 'P3' | 'P4';

// ── Recipient Types ─────────────────────────────────────────────
export type RecipientType =
  | 'assignee'
  | 'owner'
  | 'reporter'
  | 'creator'
  | 'watchers'
  | 'mentioned_users'
  | 'team_members'
  | 'project_lead'
  | 'approvers'
  | 'parent_owner'
  | 'previous_assignee'
  | 'new_assignee'
  | 'all_release_managers'
  | 'on_call_team'
  | 'escalation_target'
  | 'committee_members'
  | 'test_lead'
  | 'dev_lead'
  | 'assigned_testers'
  | 'workstream_members'
  | 'allocated_user'
  | 'category_watchers'
  | 'contributors'
  | 'previous_commenters'
  | 'affected_assignees'
  | 'both_assignees'
  | 'linked_item_assignees'
  | 'shared_with_user'
  | 'submitter'
  | 'budget_owner'
  | 'risk_owner'
  | 'product_lead'
  | 'relevant_user';

// ── Channel Types ───────────────────────────────────────────────
export type NotificationChannel = 'in_app' | 'email' | 'toast' | 'slack';

// ── Tab Routing ─────────────────────────────────────────────────
export type NotificationTabRoute = 'direct' | 'watching' | 'ai' | 'direct/watching';

// ── Notification Event Definition ───────────────────────────────
export interface NotificationEventDef {
  /** Unique trigger key — becomes notification_type in DB */
  triggerKey: string;
  /** Human-readable display name */
  displayName: string;
  /** Short description of when this fires */
  description: string;
  /** Which hub this belongs to */
  hubSource: HubSource;
  /** Grouping category for admin UI */
  category: TriggerCategory;
  /** Priority level P1-P4 */
  priority: TriggerPriority;
  /** Default recipient types */
  recipients: RecipientType[];
  /** Default notification channels */
  channels: NotificationChannel[];
  /** Which notification panel tab to route to */
  tab: NotificationTabRoute;
  /** Whether this trigger is ON by default */
  defaultEnabled: boolean;
  /** If true, users CANNOT disable this (P1 critical events) */
  isMandatory: boolean;
  /** If true, this is a silent event — no notification sent */
  isSilent: boolean;
  /** The DB entity type this relates to */
  entityType: string;
}

// ═══════════════════════════════════════════════════════════════════
// HUB 1 — STRATEGY HUB (24 events)
// ═══════════════════════════════════════════════════════════════════

export const STRATEGY_HUB_EVENTS: NotificationEventDef[] = [
  // ── Objectives ────────────────────────────────────────────────
  {
    triggerKey: 'objective_created',
    displayName: 'Objective Created',
    description: 'A new OKR objective is created',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app', 'email'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },
  {
    triggerKey: 'objective_updated',
    displayName: 'Objective Updated (Name/Description)',
    description: 'An objective name or description is modified',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },
  {
    triggerKey: 'objective_status_changed',
    displayName: 'Objective Status Changed',
    description: 'Objective status transitions (e.g. pending to in_progress)',
    hubSource: 'StrategyHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['owner', 'watchers', 'project_lead'],
    channels: ['in_app', 'email'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },
  {
    triggerKey: 'objective_health_changed',
    displayName: 'Objective Health Changed',
    description: 'Objective health indicator changes (good/fair/poor/at_risk)',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P2',
    recipients: ['owner', 'watchers', 'project_lead'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },
  {
    triggerKey: 'objective_owner_changed',
    displayName: 'Objective Owner Changed',
    description: 'Objective is reassigned to a new owner',
    hubSource: 'StrategyHub',
    category: 'assignments',
    priority: 'P2',
    recipients: ['new_assignee', 'previous_assignee', 'watchers'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },
  {
    triggerKey: 'objective_dates_changed',
    displayName: 'Objective Dates Changed',
    description: 'Objective start or end date is modified',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },
  {
    triggerKey: 'objective_deleted',
    displayName: 'Objective Deleted',
    description: 'An objective is deleted',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'objective',
  },

  // ── Key Results ───────────────────────────────────────────────
  {
    triggerKey: 'key_result_created',
    displayName: 'Key Result Created',
    description: 'A new key result is added to an objective',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'key_result',
  },
  {
    triggerKey: 'key_result_updated',
    displayName: 'Key Result Updated (Target/Value)',
    description: 'Key result target or current value is modified',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'key_result',
  },
  {
    triggerKey: 'key_result_status_changed',
    displayName: 'Key Result Status Changed',
    description: 'Key result status transitions',
    hubSource: 'StrategyHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'key_result',
  },
  {
    triggerKey: 'key_result_checkin',
    displayName: 'Key Result Check-in',
    description: 'A progress check-in is recorded for a key result',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app', 'email'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'key_result',
  },
  {
    triggerKey: 'okr_milestone_achieved',
    displayName: 'OKR Milestone Achieved (KR >= 100%)',
    description: 'A key result reaches or exceeds its target',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P1',
    recipients: ['owner', 'watchers', 'project_lead'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: true,
    isSilent: false,
    entityType: 'key_result',
  },
  {
    triggerKey: 'key_result_deleted',
    displayName: 'Key Result Deleted',
    description: 'A key result is removed from an objective',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['owner'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'key_result',
  },

  // ── Strategic Themes ──────────────────────────────────────────
  {
    triggerKey: 'theme_created',
    displayName: 'Strategic Theme Created',
    description: 'A new strategic theme is created',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['project_lead', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'theme',
  },
  {
    triggerKey: 'theme_updated',
    displayName: 'Strategic Theme Updated',
    description: 'A strategic theme is modified',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'theme',
  },
  {
    triggerKey: 'theme_deleted',
    displayName: 'Strategic Theme Deleted',
    description: 'A strategic theme is deleted',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'theme',
  },

  // ── Theme Groups ──────────────────────────────────────────────
  {
    triggerKey: 'theme_group_created',
    displayName: 'Theme Group Created',
    description: 'A new theme group is created',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'theme_group',
  },
  {
    triggerKey: 'theme_group_updated',
    displayName: 'Theme Group Updated',
    description: 'A theme group is modified',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'theme_group',
  },
  {
    triggerKey: 'theme_group_deleted',
    displayName: 'Theme Group Deleted',
    description: 'A theme group is deleted',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'theme_group',
  },

  // ── Goal-Request Links ─────────────────────────────────────
  {
    triggerKey: 'goal_initiative_linked',
    displayName: 'Goal-Request Linked',
    description: 'An initiative is linked to a goal',
    hubSource: 'StrategyHub',
    category: 'dependencies_links',
    priority: 'P3',
    recipients: ['owner', 'parent_owner'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'goal_initiative',
  },
  {
    triggerKey: 'goal_initiative_unlinked',
    displayName: 'Goal-Request Unlinked',
    description: 'An initiative is unlinked from a goal',
    hubSource: 'StrategyHub',
    category: 'dependencies_links',
    priority: 'P3',
    recipients: ['owner', 'parent_owner'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'goal_initiative',
  },

  // ── Milestones ────────────────────────────────────────────────
  {
    triggerKey: 'milestone_created',
    displayName: 'Milestone Created',
    description: 'A new milestone is added to an objective/theme',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'milestone',
  },
  {
    triggerKey: 'milestone_updated',
    displayName: 'Milestone Updated',
    description: 'A milestone is modified',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'milestone',
  },
  {
    triggerKey: 'milestone_deleted',
    displayName: 'Milestone Deleted',
    description: 'A milestone is removed',
    hubSource: 'StrategyHub',
    category: 'strategy_okrs',
    priority: 'P4',
    recipients: ['owner'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'milestone',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 2 — PRODUCT HUB (23 events)
// ═══════════════════════════════════════════════════════════════════

export const PRODUCT_HUB_EVENTS: NotificationEventDef[] = [
  // ── Features ──────────────────────────────────────────────────
  {
    triggerKey: 'feature_created',
    displayName: 'Feature Created',
    description: 'A new feature is created',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'project_lead', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_status_changed',
    displayName: 'Feature Status Changed',
    description: 'Feature status transitions',
    hubSource: 'ProductHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['owner', 'watchers', 'parent_owner'],
    channels: ['in_app', 'email'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_assigned',
    displayName: 'Feature Owner Assigned',
    description: 'A feature is assigned to an owner',
    hubSource: 'ProductHub',
    category: 'assignments',
    priority: 'P2',
    recipients: ['new_assignee', 'previous_assignee'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_priority_changed',
    displayName: 'Feature Priority Changed',
    description: 'Feature priority level is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_dates_changed',
    displayName: 'Feature Dates Changed',
    description: 'Feature start or target date is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_updated',
    displayName: 'Feature Description Updated',
    description: 'Feature description is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_contributor_added',
    displayName: 'Feature Contributor Added',
    description: 'A user is added as a contributor to a feature',
    hubSource: 'ProductHub',
    category: 'assignments',
    priority: 'P2',
    recipients: ['new_assignee'],
    channels: ['in_app', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },
  {
    triggerKey: 'feature_deleted',
    displayName: 'Feature Deleted',
    description: 'A feature is deleted',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'feature',
  },

  // ── Ideas ─────────────────────────────────────────────────────
  {
    triggerKey: 'idea_created',
    displayName: 'Idea Created',
    description: 'A new idea is submitted',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['product_lead', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'idea',
  },
  {
    triggerKey: 'idea_status_changed',
    displayName: 'Idea Status Changed',
    description: 'Idea status transitions (e.g. submitted to under_review)',
    hubSource: 'ProductHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['creator', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'idea',
  },
  {
    triggerKey: 'idea_priority_changed',
    displayName: 'Idea Priority Changed',
    description: 'Idea priority is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['creator', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'idea',
  },
  {
    triggerKey: 'idea_voted',
    displayName: 'Idea Voted/Scored',
    description: 'Someone votes on or scores an idea',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['creator'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'idea',
  },
  {
    triggerKey: 'idea_converted',
    displayName: 'Idea Converted to Request',
    description: 'An idea is promoted to an initiative',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P2',
    recipients: ['creator', 'watchers'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'idea',
  },
  {
    triggerKey: 'idea_deleted',
    displayName: 'Idea Deleted',
    description: 'An idea is deleted',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['creator'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'idea',
  },

  // ── Requests ───────────────────────────────────────────────
  {
    triggerKey: 'initiative_created',
    displayName: 'Request Created',
    description: 'A new initiative is created',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'project_lead', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'initiative',
  },
  {
    triggerKey: 'initiative_updated',
    displayName: 'Request Updated',
    description: 'An initiative is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'initiative',
  },
  {
    triggerKey: 'initiative_deleted',
    displayName: 'Request Deleted',
    description: 'An initiative is deleted',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'initiative',
  },

  // ── Business Requests ─────────────────────────────────────────
  {
    triggerKey: 'business_request_created',
    displayName: 'Business Request Created',
    description: 'A new business request is submitted',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['product_lead', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'business_request',
  },
  {
    triggerKey: 'business_request_updated',
    displayName: 'Business Request Updated',
    description: 'A business request is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'business_request',
  },
  {
    triggerKey: 'business_request_deleted',
    displayName: 'Business Request Deleted',
    description: 'A business request is deleted',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'business_request',
  },

  // ── Roadmap ───────────────────────────────────────────────────
  {
    triggerKey: 'roadmap_item_created',
    displayName: 'Roadmap Item Created',
    description: 'A new item is added to the roadmap',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'roadmap_item',
  },
  {
    triggerKey: 'roadmap_timeline_changed',
    displayName: 'Roadmap Timeline Updated',
    description: 'A roadmap item timeline is modified',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P3',
    recipients: ['owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'roadmap_item',
  },
  {
    triggerKey: 'roadmap_reordered',
    displayName: 'Roadmap Reordered',
    description: 'Roadmap items are reordered',
    hubSource: 'ProductHub',
    category: 'product_ideas',
    priority: 'P4',
    recipients: [],
    channels: [],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: true,
    entityType: 'roadmap_item',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 3 — PROJECT HUB (34 events)
// ═══════════════════════════════════════════════════════════════════

export const PROJECT_HUB_EVENTS: NotificationEventDef[] = [
  // ── Work Items (Stories/Tasks/Bugs/Epics) ─────────────────────
  {
    triggerKey: 'created_work_item',
    displayName: 'Work Item Created',
    description: 'A new work item (story, task, bug, epic) is created',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['assignee', 'reporter', 'watchers', 'parent_owner'],
    channels: ['in_app'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'assigned_work_item',
    displayName: 'Work Item Assigned',
    description: 'A work item is assigned to someone',
    hubSource: 'ProjectHub',
    category: 'assignments',
    priority: 'P2',
    recipients: ['new_assignee'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'reassigned_work_item',
    displayName: 'Work Item Reassigned',
    description: 'A work item is reassigned to a different person',
    hubSource: 'ProjectHub',
    category: 'assignments',
    priority: 'P2',
    recipients: ['new_assignee', 'previous_assignee'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'unassigned',
    displayName: 'Work Item Unassigned',
    description: 'A work item assignee is cleared',
    hubSource: 'ProjectHub',
    category: 'assignments',
    priority: 'P2',
    recipients: ['previous_assignee'],
    channels: ['in_app', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'status_changed',
    displayName: 'Work Item Status Changed',
    description: 'A work item transitions to a new status',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['assignee', 'reporter', 'watchers'],
    channels: ['in_app', 'email'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'work_item_priority_changed',
    displayName: 'Work Item Priority Changed',
    description: 'Work item priority level is modified',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'work_item_sprint_changed',
    displayName: 'Work Item Release/Sprint Changed',
    description: 'Work item is moved to a different release or sprint',
    hubSource: 'ProjectHub',
    category: 'releases',
    priority: 'P3',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'work_item_estimate_changed',
    displayName: 'Work Item Story Points Changed',
    description: 'Work item estimate/story points are modified',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'updated_work_item',
    displayName: 'Work Item Updated (Description/Title)',
    description: 'Work item description or title is modified',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'work_item_deleted',
    displayName: 'Work Item Deleted',
    description: 'A work item is deleted (soft delete)',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['assignee', 'reporter', 'watchers'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'work_item_bulk_updated',
    displayName: 'Work Items Bulk Updated',
    description: 'Multiple work items are updated in a batch operation',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['affected_assignees'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },

  // ── Dependencies ──────────────────────────────────────────────
  {
    triggerKey: 'dependency_created',
    displayName: 'Dependency Created',
    description: 'A blocking/blocked-by dependency is created between items',
    hubSource: 'ProjectHub',
    category: 'dependencies_links',
    priority: 'P2',
    recipients: ['both_assignees'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'dependency',
  },
  {
    triggerKey: 'dependency_updated',
    displayName: 'Dependency Updated',
    description: 'A dependency status or notes are modified',
    hubSource: 'ProjectHub',
    category: 'dependencies_links',
    priority: 'P3',
    recipients: ['both_assignees'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'dependency',
  },
  {
    triggerKey: 'dependency_deleted',
    displayName: 'Dependency Deleted',
    description: 'A dependency link is removed',
    hubSource: 'ProjectHub',
    category: 'dependencies_links',
    priority: 'P3',
    recipients: ['both_assignees'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'dependency',
  },

  // ── Comments & Mentions ───────────────────────────────────────
  {
    triggerKey: 'commented_on_work_item',
    displayName: 'Comment Added',
    description: 'A comment is posted on a work item',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P3',
    recipients: ['assignee', 'reporter', 'watchers', 'previous_commenters'],
    channels: ['in_app', 'email'],
    tab: 'direct/watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'mentioned_in_comment',
    displayName: '@Mention in Comment',
    description: 'A user is @mentioned in a comment (always fires, bypasses prefs)',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P2',
    recipients: ['mentioned_users'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: true,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'comment_updated',
    displayName: 'Comment Edited',
    description: 'A comment is edited (notifies new @mentions if any)',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P3',
    recipients: ['mentioned_users'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'comment_deleted',
    displayName: 'Comment Deleted',
    description: 'A comment is removed',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P4',
    recipients: [],
    channels: [],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: true,
    entityType: 'work_item',
  },

  // ── Attachments ───────────────────────────────────────────────
  {
    triggerKey: 'attachment_added',
    displayName: 'Attachment Uploaded',
    description: 'A file is attached to a work item',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P4',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'attachment_deleted',
    displayName: 'Attachment Deleted',
    description: 'An attachment is removed from a work item',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },

  // ── Watchers ──────────────────────────────────────────────────
  {
    triggerKey: 'watcher_added',
    displayName: 'Watcher Added',
    description: 'A user is added as a watcher on a work item',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P4',
    recipients: ['new_assignee'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'watcher_removed',
    displayName: 'Watcher Removed',
    description: 'A user is removed from watchers',
    hubSource: 'ProjectHub',
    category: 'comments_mentions',
    priority: 'P4',
    recipients: [],
    channels: [],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: true,
    entityType: 'work_item',
  },

  // ── Labels ────────────────────────────────────────────────────
  {
    triggerKey: 'label_added',
    displayName: 'Label Added',
    description: 'A label is added to a work item',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'label_removed',
    displayName: 'Label Removed',
    description: 'A label is removed from a work item',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },

  // ── Links ─────────────────────────────────────────────────────
  {
    triggerKey: 'link_created',
    displayName: 'Link Created',
    description: 'A link is created between work items',
    hubSource: 'ProjectHub',
    category: 'dependencies_links',
    priority: 'P4',
    recipients: ['linked_item_assignees'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },
  {
    triggerKey: 'link_deleted',
    displayName: 'Link Deleted',
    description: 'A link between work items is removed',
    hubSource: 'ProjectHub',
    category: 'dependencies_links',
    priority: 'P4',
    recipients: ['linked_item_assignees'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },

  // ── Subtasks ──────────────────────────────────────────────────
  {
    triggerKey: 'subtask_created',
    displayName: 'Subtask Created',
    description: 'A subtask is added to a work item',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P3',
    recipients: ['parent_owner'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'subtask',
  },
  {
    triggerKey: 'subtask_updated',
    displayName: 'Subtask Updated',
    description: 'A subtask is modified',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['parent_owner', 'watchers'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'subtask',
  },
  {
    triggerKey: 'subtask_deleted',
    displayName: 'Subtask Deleted',
    description: 'A subtask is removed',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['parent_owner'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'subtask',
  },

  // ── Due Date ──────────────────────────────────────────────────
  {
    triggerKey: 'due_date_approaching',
    displayName: 'Due Date Approaching (3 days)',
    description: 'A work item due date is within 3 days',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P2',
    recipients: ['assignee'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true,
    isMandatory: false,
    isSilent: false,
    entityType: 'work_item',
  },

  // ── Board ─────────────────────────────────────────────────────
  {
    triggerKey: 'board_created',
    displayName: 'Board Created',
    description: 'A new board is created in the project',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['team_members'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'board',
  },
  {
    triggerKey: 'board_updated',
    displayName: 'Board Updated',
    description: 'Board columns or configuration is modified',
    hubSource: 'ProjectHub',
    category: 'status_changes',
    priority: 'P4',
    recipients: ['team_members'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: false,
    isMandatory: false,
    isSilent: false,
    entityType: 'board',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 4 — RELEASE HUB (15 events)
// ═══════════════════════════════════════════════════════════════════

export const RELEASE_HUB_EVENTS: NotificationEventDef[] = [
  {
    triggerKey: 'release_created',
    displayName: 'Release Created',
    description: 'A new release is created',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P3',
    recipients: ['team_members', 'watchers'],
    channels: ['in_app', 'email'],
    tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'release',
  },
  {
    triggerKey: 'release_status_changed',
    displayName: 'Release Status Changed',
    description: 'Release status transitions (e.g. planning to active)',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P2',
    recipients: ['team_members', 'watchers'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'release',
  },
  {
    triggerKey: 'release_test_linked',
    displayName: 'Test Cycle Linked to Release',
    description: 'A test cycle is linked to a release',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P3',
    recipients: ['team_members', 'test_lead'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'release',
  },
  {
    triggerKey: 'release_test_unlinked',
    displayName: 'Test Cycle Unlinked from Release',
    description: 'A test cycle is unlinked from a release',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P3',
    recipients: ['team_members', 'test_lead'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'release',
  },
  {
    triggerKey: 'change_created',
    displayName: 'Change Request Created',
    description: 'A new change request is submitted',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P2',
    recipients: ['approvers'],
    channels: ['in_app', 'email'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'change',
  },
  {
    triggerKey: 'change_status_changed',
    displayName: 'Change Request Status Changed',
    description: 'A change request status transitions',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P2',
    recipients: ['creator', 'approvers', 'watchers'],
    channels: ['in_app', 'email'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'change',
  },
  {
    triggerKey: 'change_work_items_linked',
    displayName: 'Work Items Linked to Change',
    description: 'Work items are associated with a change request',
    hubSource: 'ReleaseHub',
    category: 'dependencies_links',
    priority: 'P3',
    recipients: ['owner', 'linked_item_assignees'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'change',
  },
  {
    triggerKey: 'change_release_linked',
    displayName: 'Change Linked to Release',
    description: 'A change request is assigned to a release',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P3',
    recipients: ['owner'],
    channels: ['in_app'],
    tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'change',
  },
  {
    triggerKey: 'release_approval_requested',
    displayName: 'Sign-off Requested',
    description: 'A release sign-off approval is requested',
    hubSource: 'ReleaseHub',
    category: 'approvals_signoffs',
    priority: 'P1',
    recipients: ['approvers'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false,
    entityType: 'signoff',
  },
  {
    triggerKey: 'release_approved',
    displayName: 'Sign-off Approved',
    description: 'A release sign-off is approved',
    hubSource: 'ReleaseHub',
    category: 'approvals_signoffs',
    priority: 'P1',
    recipients: ['creator', 'watchers'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false,
    entityType: 'signoff',
  },
  {
    triggerKey: 'release_rejected',
    displayName: 'Sign-off Rejected',
    description: 'A release sign-off is rejected',
    hubSource: 'ReleaseHub',
    category: 'approvals_signoffs',
    priority: 'P1',
    recipients: ['creator', 'watchers'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false,
    entityType: 'signoff',
  },
  {
    triggerKey: 'freeze_window_created',
    displayName: 'Freeze Window Created',
    description: 'A code/deployment freeze window is established',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P2',
    recipients: ['all_release_managers', 'team_members'],
    channels: ['in_app', 'email'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'freeze_window',
  },
  {
    triggerKey: 'freeze_window_deleted',
    displayName: 'Freeze Window Deleted',
    description: 'A freeze window is removed',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P3',
    recipients: ['all_release_managers'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'freeze_window',
  },
  {
    triggerKey: 'production_event_created',
    displayName: 'Production Event Created',
    description: 'A production deployment or event is logged',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P1',
    recipients: ['all_release_managers', 'on_call_team'],
    channels: ['in_app', 'email', 'toast'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false,
    entityType: 'production_event',
  },
  {
    triggerKey: 'triage_change_linked',
    displayName: 'Triage: Change Linked to Release',
    description: 'An unlinked change is triaged and assigned to a release',
    hubSource: 'ReleaseHub',
    category: 'releases',
    priority: 'P2',
    recipients: ['owner'],
    channels: ['in_app'],
    tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false,
    entityType: 'change',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 5 — TEST HUB (31 events)
// ═══════════════════════════════════════════════════════════════════

export const TEST_HUB_EVENTS: NotificationEventDef[] = [
  // ── Test Cases ────────────────────────────────────────────────
  {
    triggerKey: 'test_case_created',
    displayName: 'Test Case Created',
    description: 'A new test case is created',
    hubSource: 'TestHub', category: 'testing', priority: 'P3',
    recipients: ['test_lead', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'test_case_updated',
    displayName: 'Test Case Updated',
    description: 'A test case title, description, or fields are modified',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'test_case_moved',
    displayName: 'Test Case Moved to Folder',
    description: 'A test case is moved to a different folder',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'test_case_deleted',
    displayName: 'Test Case Deleted',
    description: 'A test case is deleted',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'test_steps_changed',
    displayName: 'Test Steps Changed',
    description: 'Test steps are created, updated, or deleted',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_case',
  },

  // ── Test Plans ────────────────────────────────────────────────
  {
    triggerKey: 'test_plan_created',
    displayName: 'Test Plan Created',
    description: 'A new test plan is created',
    hubSource: 'TestHub', category: 'testing', priority: 'P3',
    recipients: ['test_lead', 'team_members'],
    channels: ['in_app', 'email'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_plan',
  },
  {
    triggerKey: 'test_plan_status_changed',
    displayName: 'Test Plan Status Changed',
    description: 'A test plan status transitions',
    hubSource: 'TestHub', category: 'status_changes', priority: 'P3',
    recipients: ['test_lead', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_plan',
  },
  {
    triggerKey: 'test_plan_deleted',
    displayName: 'Test Plan Deleted',
    description: 'A test plan is deleted',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['test_lead'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_plan',
  },

  // ── Test Cycles ───────────────────────────────────────────────
  {
    triggerKey: 'test_cycle_created',
    displayName: 'Test Cycle Created',
    description: 'A new test cycle/run is created',
    hubSource: 'TestHub', category: 'testing', priority: 'P2',
    recipients: ['assigned_testers', 'test_lead'],
    channels: ['in_app', 'email'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_cycle',
  },
  {
    triggerKey: 'tester_assigned',
    displayName: 'Tester Assigned to Cycle',
    description: 'A tester is assigned to a test cycle',
    hubSource: 'TestHub', category: 'assignments', priority: 'P2',
    recipients: ['new_assignee'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_cycle',
  },
  {
    triggerKey: 'test_execution_passed',
    displayName: 'Test Execution: Pass',
    description: 'A test case execution result is marked as passed',
    hubSource: 'TestHub', category: 'testing', priority: 'P3',
    recipients: ['test_lead', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_execution',
  },
  {
    triggerKey: 'test_case_failed',
    displayName: 'Test Execution: Fail',
    description: 'A test case execution result is marked as failed',
    hubSource: 'TestHub', category: 'testing', priority: 'P2',
    recipients: ['test_lead', 'assignee', 'watchers'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_execution',
  },
  {
    triggerKey: 'test_cycle_status_changed',
    displayName: 'Test Cycle Status Changed',
    description: 'A test cycle transitions status (draft/active/paused/completed)',
    hubSource: 'TestHub', category: 'status_changes', priority: 'P3',
    recipients: ['test_lead', 'assigned_testers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_cycle',
  },
  {
    triggerKey: 'tests_added_to_cycle',
    displayName: 'Tests Added to Cycle',
    description: 'Test cases are added to a test cycle',
    hubSource: 'TestHub', category: 'testing', priority: 'P3',
    recipients: ['assigned_testers'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_cycle',
  },

  // ── Test Sets ─────────────────────────────────────────────────
  {
    triggerKey: 'test_set_created',
    displayName: 'Test Set Created',
    description: 'A new test set is created',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['test_lead'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_set',
  },
  {
    triggerKey: 'test_set_updated',
    displayName: 'Test Set Updated',
    description: 'A test set is modified',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_set',
  },
  {
    triggerKey: 'test_set_deleted',
    displayName: 'Test Set Deleted',
    description: 'A test set is deleted',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_set',
  },
  {
    triggerKey: 'test_set_cases_changed',
    displayName: 'Test Cases Added/Removed from Set',
    description: 'Test cases are added to or removed from a test set',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['test_lead'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_set',
  },

  // ── Test Folders (mostly silent) ──────────────────────────────
  {
    triggerKey: 'test_folder_created',
    displayName: 'Test Folder Created',
    description: 'A new test folder is created',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'test_folder',
  },
  {
    triggerKey: 'test_folder_renamed',
    displayName: 'Test Folder Renamed',
    description: 'A test folder is renamed',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'test_folder',
  },
  {
    triggerKey: 'test_folder_deleted',
    displayName: 'Test Folder Deleted',
    description: 'A test folder and its contents are deleted',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_folder',
  },
  {
    triggerKey: 'test_folder_moved',
    displayName: 'Test Folder Moved',
    description: 'A test folder is moved to a different parent',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'test_folder',
  },

  // ── Defects ───────────────────────────────────────────────────
  {
    triggerKey: 'defect_created',
    displayName: 'Defect Created from Test',
    description: 'A defect is created from a failed test execution',
    hubSource: 'TestHub', category: 'testing', priority: 'P2',
    recipients: ['test_lead', 'assignee', 'dev_lead'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'defect',
  },
  {
    triggerKey: 'defect_updated',
    displayName: 'Defect Updated',
    description: 'A defect is modified',
    hubSource: 'TestHub', category: 'testing', priority: 'P3',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'defect',
  },
  {
    triggerKey: 'defect_test_linked',
    displayName: 'Defect Linked to Test Case',
    description: 'A defect is linked to a test case',
    hubSource: 'TestHub', category: 'dependencies_links', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'defect',
  },

  // ── Gherkin & Requirements ────────────────────────────────────
  {
    triggerKey: 'gherkin_steps_changed',
    displayName: 'Gherkin Steps Changed',
    description: 'Gherkin (BDD) steps are modified on a test case',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'requirement_linked',
    displayName: 'Requirement Linked to Test Case',
    description: 'A requirement is linked to a test case for traceability',
    hubSource: 'TestHub', category: 'dependencies_links', priority: 'P3',
    recipients: ['assignee', 'owner'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'requirement_unlinked',
    displayName: 'Requirement Unlinked from Test Case',
    description: 'A requirement link is removed from a test case',
    hubSource: 'TestHub', category: 'dependencies_links', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_case',
  },

  // ── Test Attachments ──────────────────────────────────────────
  {
    triggerKey: 'test_attachment_added',
    displayName: 'Test Attachment Uploaded',
    description: 'A file is attached to a test case',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'test_case',
  },
  {
    triggerKey: 'test_attachment_deleted',
    displayName: 'Test Attachment Deleted',
    description: 'An attachment is removed from a test case',
    hubSource: 'TestHub', category: 'testing', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'test_case',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 6 — INCIDENT HUB (24 events)
// ═══════════════════════════════════════════════════════════════════

export const INCIDENT_HUB_EVENTS: NotificationEventDef[] = [
  {
    triggerKey: 'incident_created',
    displayName: 'Incident Created',
    description: 'A new incident is reported',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['team_members', 'on_call_team', 'watchers'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_status_changed',
    displayName: 'Incident Status Changed',
    description: 'Incident status transitions (open/in-progress/resolved/closed)',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['assignee', 'team_members', 'watchers', 'reporter'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_severity_changed',
    displayName: 'Incident Severity Changed',
    description: 'Incident severity level is modified (SEV1-SEV4)',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['assignee', 'team_members', 'watchers', 'project_lead'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_assigned',
    displayName: 'Incident Assignee Changed',
    description: 'Incident is assigned or reassigned',
    hubSource: 'IncidentHub', category: 'assignments', priority: 'P1',
    recipients: ['new_assignee', 'previous_assignee'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_updated',
    displayName: 'Incident Description Updated',
    description: 'Incident description or details are modified',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P3',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_support_level_changed',
    displayName: 'Incident Support Level Changed',
    description: 'Incident support level transitions (L1/L2/L3)',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P2',
    recipients: ['assignee', 'team_members'],
    channels: ['in_app', 'email'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_delivery_stage_changed',
    displayName: 'Incident Delivery Stage Changed',
    description: 'Incident delivery stage is modified',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P2',
    recipients: ['assignee', 'team_members'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_escalated',
    displayName: 'Incident Escalated',
    description: 'An incident is escalated to higher support or management',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['escalation_target', 'project_lead', 'team_members'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_deleted',
    displayName: 'Incident Soft Deleted',
    description: 'An incident is soft-deleted',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P3',
    recipients: ['assignee', 'reporter'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_comment_update',
    displayName: 'Incident Comment (Update)',
    description: 'An update comment is posted on an incident',
    hubSource: 'IncidentHub', category: 'comments_mentions', priority: 'P2',
    recipients: ['assignee', 'team_members', 'watchers'],
    channels: ['in_app', 'email'], tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_root_cause_added',
    displayName: 'Incident Root Cause Added',
    description: 'A root cause comment is posted on an incident',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P2',
    recipients: ['assignee', 'team_members', 'watchers', 'project_lead'],
    channels: ['in_app', 'email'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_resolution_added',
    displayName: 'Incident Resolution Added',
    description: 'A resolution comment is posted on an incident',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['assignee', 'team_members', 'watchers', 'reporter'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_team_assigned',
    displayName: 'Incident Team Assigned',
    description: 'A team is assigned to handle an incident',
    hubSource: 'IncidentHub', category: 'assignments', priority: 'P1',
    recipients: ['team_members'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_team_removed',
    displayName: 'Incident Team Removed',
    description: 'A team is removed from an incident',
    hubSource: 'IncidentHub', category: 'assignments', priority: 'P3',
    recipients: ['team_members'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_watcher_added',
    displayName: 'Incident Watcher Added',
    description: 'A user is added as a watcher on an incident',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P4',
    recipients: ['new_assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_attachment_added',
    displayName: 'Incident Attachment Uploaded',
    description: 'A file is attached to an incident',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P3',
    recipients: ['assignee', 'team_members'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_work_item_linked',
    displayName: 'Incident Work Item Linked',
    description: 'A work item is linked to an incident',
    hubSource: 'IncidentHub', category: 'dependencies_links', priority: 'P3',
    recipients: ['assignee', 'linked_item_assignees'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'incident_work_item_unlinked',
    displayName: 'Incident Work Item Unlinked',
    description: 'A work item link is removed from an incident',
    hubSource: 'IncidentHub', category: 'dependencies_links', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'sla_created',
    displayName: 'SLA Record Created',
    description: 'An SLA record is created for an incident',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P3',
    recipients: ['assignee', 'team_members'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'sla',
  },
  {
    triggerKey: 'sla_breach_warning',
    displayName: 'SLA Breach Warning (80%)',
    description: 'An SLA is at 80% of its allowed time',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['assignee', 'team_members', 'project_lead'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'sla',
  },
  {
    triggerKey: 'sla_breached',
    displayName: 'SLA Breached',
    description: 'An SLA has been breached',
    hubSource: 'IncidentHub', category: 'incidents_sla', priority: 'P1',
    recipients: ['assignee', 'team_members', 'project_lead', 'escalation_target'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'sla',
  },
  {
    triggerKey: 'committee_submitted',
    displayName: 'Committee Queue Submitted',
    description: 'An incident is submitted for committee review',
    hubSource: 'IncidentHub', category: 'approvals_signoffs', priority: 'P2',
    recipients: ['committee_members'],
    channels: ['in_app', 'email'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'committee_approved',
    displayName: 'Committee Approved',
    description: 'An incident committee review is approved',
    hubSource: 'IncidentHub', category: 'approvals_signoffs', priority: 'P1',
    recipients: ['submitter', 'assignee'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
  {
    triggerKey: 'committee_rejected',
    displayName: 'Committee Rejected',
    description: 'An incident committee review is rejected',
    hubSource: 'IncidentHub', category: 'approvals_signoffs', priority: 'P1',
    recipients: ['submitter', 'assignee'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'incident',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 7 — TASK HUB / WORKHUB (11 events)
// ═══════════════════════════════════════════════════════════════════

export const TASK_HUB_EVENTS: NotificationEventDef[] = [
  {
    triggerKey: 'task_created',
    displayName: 'Task Created',
    description: 'A new task is created in TaskHub',
    hubSource: 'TaskHub', category: 'assignments', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_assigned',
    displayName: 'Task Assigned',
    description: 'A task is assigned to someone',
    hubSource: 'TaskHub', category: 'assignments', priority: 'P2',
    recipients: ['new_assignee'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_status_changed',
    displayName: 'Task Status Changed',
    description: 'A task status transitions (todo/done)',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P3',
    recipients: ['assignee', 'reporter', 'watchers'],
    channels: ['in_app'], tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_priority_changed',
    displayName: 'Task Priority Changed',
    description: 'A task priority is modified',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_dates_changed',
    displayName: 'Task Due Date Changed',
    description: 'A task due date is modified',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_deleted',
    displayName: 'Task Deleted',
    description: 'A task is soft-deleted',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_restored',
    displayName: 'Task Restored',
    description: 'A soft-deleted task is restored',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_bulk_updated',
    displayName: 'Tasks Bulk Updated',
    description: 'Multiple tasks are updated in a batch operation',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P3',
    recipients: ['affected_assignees'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_commented',
    displayName: 'Task Comment Created',
    description: 'A comment is posted on a task',
    hubSource: 'TaskHub', category: 'comments_mentions', priority: 'P3',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'], tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_label_changed',
    displayName: 'Task Label Added/Removed',
    description: 'Labels are changed on a task',
    hubSource: 'TaskHub', category: 'status_changes', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'task_view_changed',
    displayName: 'View/Filter Created/Updated/Deleted',
    description: 'A saved view or filter is changed (personal, usually silent)',
    hubSource: 'TaskHub', category: 'system_ai', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'view',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 8 — PLAN HUB (12 events)
// ═══════════════════════════════════════════════════════════════════

export const PLAN_HUB_EVENTS: NotificationEventDef[] = [
  {
    triggerKey: 'planner_task_created',
    displayName: 'Planner Task Created',
    description: 'A new planner task is created',
    hubSource: 'PlanHub', category: 'planning', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'planner_task',
  },
  {
    triggerKey: 'planner_task_assigned',
    displayName: 'Planner Task Assigned',
    description: 'A planner task is assigned to someone',
    hubSource: 'PlanHub', category: 'assignments', priority: 'P2',
    recipients: ['new_assignee'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'planner_task',
  },
  {
    triggerKey: 'planner_task_status_changed',
    displayName: 'Planner Task Status Changed',
    description: 'A planner task status transitions',
    hubSource: 'PlanHub', category: 'status_changes', priority: 'P3',
    recipients: ['assignee', 'watchers'],
    channels: ['in_app'], tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'planner_task',
  },
  {
    triggerKey: 'planner_task_dates_changed',
    displayName: 'Planner Task Dates Changed',
    description: 'A planner task dates are modified',
    hubSource: 'PlanHub', category: 'planning', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'planner_task',
  },
  {
    triggerKey: 'planner_task_workstream_changed',
    displayName: 'Planner Task Workstream Changed',
    description: 'A planner task is moved to a different workstream',
    hubSource: 'PlanHub', category: 'planning', priority: 'P4',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'planner_task',
  },
  {
    triggerKey: 'planner_task_deleted',
    displayName: 'Planner Task Deleted',
    description: 'A planner task is deleted',
    hubSource: 'PlanHub', category: 'planning', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'planner_task',
  },
  {
    triggerKey: 'workstream_created',
    displayName: 'Workstream Created',
    description: 'A new workstream is created',
    hubSource: 'PlanHub', category: 'planning', priority: 'P4',
    recipients: ['workstream_members'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'workstream',
  },
  {
    triggerKey: 'workstream_updated',
    displayName: 'Workstream Updated',
    description: 'A workstream is modified',
    hubSource: 'PlanHub', category: 'planning', priority: 'P4',
    recipients: ['workstream_members'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'workstream',
  },
  {
    triggerKey: 'workstream_deleted',
    displayName: 'Workstream Deleted',
    description: 'A workstream is deleted',
    hubSource: 'PlanHub', category: 'planning', priority: 'P4',
    recipients: ['workstream_members'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'workstream',
  },
  {
    triggerKey: 'allocation_created',
    displayName: 'Resource Allocation Created',
    description: 'A resource allocation is created',
    hubSource: 'PlanHub', category: 'assignments', priority: 'P3',
    recipients: ['allocated_user'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'allocation',
  },
  {
    triggerKey: 'allocation_updated',
    displayName: 'Resource Allocation Updated',
    description: 'A resource allocation is modified',
    hubSource: 'PlanHub', category: 'assignments', priority: 'P3',
    recipients: ['allocated_user'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'allocation',
  },
  {
    triggerKey: 'allocation_deleted',
    displayName: 'Resource Allocation Deleted',
    description: 'A resource allocation is removed',
    hubSource: 'PlanHub', category: 'assignments', priority: 'P3',
    recipients: ['allocated_user'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'allocation',
  },
];

// ═══════════════════════════════════════════════════════════════════
// HUB 9 — WIKI HUB (13 events)
// ═══════════════════════════════════════════════════════════════════

export const WIKI_HUB_EVENTS: NotificationEventDef[] = [
  {
    triggerKey: 'document_created',
    displayName: 'Wiki Article Created',
    description: 'A new wiki article is created',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: ['category_watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'document_updated',
    displayName: 'Wiki Article Updated (Content)',
    description: 'A wiki article content is modified',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P3',
    recipients: ['watchers', 'contributors'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'document_renamed',
    displayName: 'Wiki Article Renamed',
    description: 'A wiki article title is changed',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'document_deleted',
    displayName: 'Wiki Article Deleted',
    description: 'A wiki article is deleted',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P3',
    recipients: ['creator', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'document_archived',
    displayName: 'Wiki Article Archived',
    description: 'A wiki article is archived',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P3',
    recipients: ['creator', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'wiki_category_created',
    displayName: 'Wiki Category Created',
    description: 'A new wiki category is created',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'wiki_category',
  },
  {
    triggerKey: 'wiki_category_updated',
    displayName: 'Wiki Category Updated',
    description: 'A wiki category is modified',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: [], channels: [], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: true, entityType: 'wiki_category',
  },
  {
    triggerKey: 'wiki_category_deleted',
    displayName: 'Wiki Category Deleted',
    description: 'A wiki category is deleted',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: ['category_watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'wiki_category',
  },
  {
    triggerKey: 'kb_document_created',
    displayName: 'KB Document Created',
    description: 'A new knowledge base document is created',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'kb_document_updated',
    displayName: 'KB Document Updated',
    description: 'A knowledge base document is modified',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P4',
    recipients: ['watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'kb_document_deleted',
    displayName: 'KB Document Deleted',
    description: 'A knowledge base document is deleted',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P3',
    recipients: ['creator', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'document_comment_added',
    displayName: 'Document Comment Added',
    description: 'A comment is posted on a wiki/KB document',
    hubSource: 'WikiHub', category: 'comments_mentions', priority: 'P3',
    recipients: ['creator', 'watchers'],
    channels: ['in_app'], tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'document',
  },
  {
    triggerKey: 'document_shared',
    displayName: 'Document Shared',
    description: 'A document is shared with a specific user',
    hubSource: 'WikiHub', category: 'documents_wiki', priority: 'P2',
    recipients: ['shared_with_user'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'document',
  },
];

// ═══════════════════════════════════════════════════════════════════
// CROSS-HUB OPERATIONS (11 events)
// ═══════════════════════════════════════════════════════════════════

export const CROSS_HUB_EVENTS: NotificationEventDef[] = [
  {
    triggerKey: 'cross_hub_mentioned_in_comment',
    displayName: '@Mention in Any Comment',
    description: '@mention in any hub comment — always fires, bypasses preferences',
    hubSource: 'CrossHub', category: 'comments_mentions', priority: 'P2',
    recipients: ['mentioned_users'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'cross_hub_watcher_added',
    displayName: 'Watcher Added (Any Entity)',
    description: 'A user is added as a watcher on any entity',
    hubSource: 'CrossHub', category: 'comments_mentions', priority: 'P4',
    recipients: ['new_assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'cross_hub_attachment_added',
    displayName: 'Attachment Uploaded (Any Entity)',
    description: 'A file is attached to any entity across hubs',
    hubSource: 'CrossHub', category: 'comments_mentions', priority: 'P4',
    recipients: ['owner', 'assignee'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: false, isMandatory: false, isSilent: false, entityType: 'work_item',
  },
  {
    triggerKey: 'team_member_added',
    displayName: 'Team Member Added',
    description: 'A user is added to a team',
    hubSource: 'CrossHub', category: 'assignments', priority: 'P2',
    recipients: ['new_assignee'],
    channels: ['in_app', 'email'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'team',
  },
  {
    triggerKey: 'team_member_removed',
    displayName: 'Team Member Removed',
    description: 'A user is removed from a team',
    hubSource: 'CrossHub', category: 'assignments', priority: 'P3',
    recipients: ['previous_assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'team',
  },
  {
    triggerKey: 'team_member_role_changed',
    displayName: 'Team Member Role Changed',
    description: 'A team member role is modified',
    hubSource: 'CrossHub', category: 'assignments', priority: 'P3',
    recipients: ['assignee'],
    channels: ['in_app'], tab: 'direct',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'team',
  },
  {
    triggerKey: 'discussion_created',
    displayName: 'Discussion Created',
    description: 'A new discussion thread is started',
    hubSource: 'CrossHub', category: 'comments_mentions', priority: 'P3',
    recipients: ['team_members', 'watchers'],
    channels: ['in_app'], tab: 'watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'discussion',
  },
  {
    triggerKey: 'discussion_reply',
    displayName: 'Discussion Reply',
    description: 'A reply is posted to a discussion thread',
    hubSource: 'CrossHub', category: 'comments_mentions', priority: 'P3',
    recipients: ['creator', 'previous_commenters', 'watchers'],
    channels: ['in_app', 'email'], tab: 'direct/watching',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'discussion',
  },
  {
    triggerKey: 'ai_insight_generated',
    displayName: 'AI Insight Generated',
    description: 'An AI-generated insight or recommendation is available',
    hubSource: 'CrossHub', category: 'system_ai', priority: 'P4',
    recipients: ['relevant_user'],
    channels: ['in_app'], tab: 'ai',
    defaultEnabled: true, isMandatory: false, isSilent: false, entityType: 'ai_insight',
  },
  {
    triggerKey: 'risk_threshold_breached',
    displayName: 'Risk Threshold Breached',
    description: 'A project risk threshold has been breached',
    hubSource: 'CrossHub', category: 'system_ai', priority: 'P1',
    recipients: ['project_lead', 'risk_owner'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'risk',
  },
  {
    triggerKey: 'budget_exceeded',
    displayName: 'Budget Exceeded',
    description: 'A project budget threshold has been exceeded',
    hubSource: 'CrossHub', category: 'system_ai', priority: 'P1',
    recipients: ['project_lead', 'budget_owner'],
    channels: ['in_app', 'email', 'toast'], tab: 'direct',
    defaultEnabled: true, isMandatory: true, isSilent: false, entityType: 'budget',
  },
];

// ═══════════════════════════════════════════════════════════════════
// MASTER REGISTRY — All events combined
// ═══════════════════════════════════════════════════════════════════

/** All 198 notification events across all hubs */
export const ALL_NOTIFICATION_EVENTS: NotificationEventDef[] = [
  ...STRATEGY_HUB_EVENTS,
  ...PRODUCT_HUB_EVENTS,
  ...PROJECT_HUB_EVENTS,
  ...RELEASE_HUB_EVENTS,
  ...TEST_HUB_EVENTS,
  ...INCIDENT_HUB_EVENTS,
  ...TASK_HUB_EVENTS,
  ...PLAN_HUB_EVENTS,
  ...WIKI_HUB_EVENTS,
  ...CROSS_HUB_EVENTS,
];

/** Lookup map: triggerKey -> event definition */
export const NOTIFICATION_EVENT_MAP: Record<string, NotificationEventDef> =
  ALL_NOTIFICATION_EVENTS.reduce((acc, evt) => {
    acc[evt.triggerKey] = evt;
    return acc;
  }, {} as Record<string, NotificationEventDef>);

/** Get all events for a specific hub */
export function getEventsByHub(hub: HubSource): NotificationEventDef[] {
  return ALL_NOTIFICATION_EVENTS.filter((e) => e.hubSource === hub);
}

/** Get all events for a specific category */
export function getEventsByCategory(category: TriggerCategory): NotificationEventDef[] {
  return ALL_NOTIFICATION_EVENTS.filter((e) => e.category === category);
}

/** Get all mandatory events (cannot be disabled by users) */
export function getMandatoryEvents(): NotificationEventDef[] {
  return ALL_NOTIFICATION_EVENTS.filter((e) => e.isMandatory);
}

/** Get all non-silent events (events that actually produce notifications) */
export function getActiveEvents(): NotificationEventDef[] {
  return ALL_NOTIFICATION_EVENTS.filter((e) => !e.isSilent);
}

/** All hub source values */
export const HUB_SOURCES: HubSource[] = [
  'StrategyHub', 'ProductHub', 'ProjectHub', 'ReleaseHub',
  'TestHub', 'IncidentHub', 'TaskHub', 'PlanHub', 'WikiHub', 'CrossHub',
];

/** All trigger category values with display labels */
export const TRIGGER_CATEGORIES: { key: TriggerCategory; label: string; count: number }[] = [
  { key: 'assignments', label: 'Assignments', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'assignments').length },
  { key: 'status_changes', label: 'Status Changes', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'status_changes').length },
  { key: 'comments_mentions', label: 'Comments & Mentions', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'comments_mentions').length },
  { key: 'approvals_signoffs', label: 'Approvals & Sign-offs', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'approvals_signoffs').length },
  { key: 'incidents_sla', label: 'Incidents & SLA', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'incidents_sla').length },
  { key: 'testing', label: 'Testing', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'testing').length },
  { key: 'strategy_okrs', label: 'Strategy & OKRs', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'strategy_okrs').length },
  { key: 'documents_wiki', label: 'Documents & Wiki', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'documents_wiki').length },
  { key: 'dependencies_links', label: 'Dependencies & Links', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'dependencies_links').length },
  { key: 'system_ai', label: 'System & AI', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'system_ai').length },
  { key: 'releases', label: 'Releases', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'releases').length },
  { key: 'planning', label: 'Planning', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'planning').length },
  { key: 'product_ideas', label: 'Product & Ideas', count: ALL_NOTIFICATION_EVENTS.filter(e => e.category === 'product_ideas').length },
];
