import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import type { Json } from '@/integrations/supabase/types';

export type DraftStatus = 'draft' | 'in_progress' | 'review' | 'approved' | 'published' | 'archived';
export type DraftLanguage = 'ar' | 'en' | 'mixed';
export type DraftDir = 'rtl' | 'ltr';
export type ComplianceVerdict = 'pass' | 'fail' | 'pending' | 'na' | null;

export interface AIAssistDraft {
  id: string;
  draft_key: string;
  title: string;
  language: DraftLanguage;
  dir: DraftDir;
  status: DraftStatus;
  current_step: number;
  step_data: Json;
  prompt_pack_version: string | null;
  sources_pack_version: string | null;
  compliance_verdict: ComplianceVerdict;
  quality_score: number | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface CreateDraftInput {
  title: string;
  language?: DraftLanguage;
  dir?: DraftDir;
}

export interface UpdateDraftInput {
  title?: string;
  language?: DraftLanguage;
  dir?: DraftDir;
  status?: DraftStatus;
  current_step?: number;
  step_data?: Json;
  prompt_pack_version?: string;
  sources_pack_version?: string;
  compliance_verdict?: ComplianceVerdict;
  quality_score?: number;
}

// Fetch all non-deleted drafts
export function useAIAssistDrafts() {
  return useQuery({
    queryKey: ['ai-assist-drafts'],
    queryFn: async (): Promise<AIAssistDraft[]> => {
      const { data, error } = await supabase
        .from('ai_assist_drafts')
        .select('*')
        .is('deleted_at', null)
        .order('updated_at', { ascending: false });

      if (error) throw error;
      return data as AIAssistDraft[];
    },
  });
}

// Fetch a single draft by ID or draft_key
export function useAIAssistDraft(draftIdOrKey: string | undefined) {
  return useQuery({
    queryKey: ['ai-assist-draft', draftIdOrKey],
    queryFn: async (): Promise<AIAssistDraft | null> => {
      if (!draftIdOrKey) return null;

      // Try to find by id first, then by draft_key
      let query = supabase
        .from('ai_assist_drafts')
        .select('*')
        .is('deleted_at', null);

      // Check if it looks like a UUID or a draft_key (AID-XXXX)
      if (draftIdOrKey.startsWith('AID-')) {
        query = query.eq('draft_key', draftIdOrKey);
      } else {
        query = query.eq('id', draftIdOrKey);
      }

      const { data, error } = await query.maybeSingle();
      if (error) throw error;
      return data as AIAssistDraft | null;
    },
    enabled: !!draftIdOrKey,
  });
}

// Create a new draft
export function useCreateDraft() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: CreateDraftInput): Promise<AIAssistDraft> => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;

      const { data, error } = await supabase
        .from('ai_assist_drafts')
        .insert({
          title: input.title,
          language: input.language || 'ar',
          dir: input.dir || 'rtl',
          created_by: userId,
          draft_key: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      // Log audit event
      await logAuditEvent(data.id, null, 'draft_created', userId, { title: input.title });

      return data as AIAssistDraft;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-assist-drafts'] });
      toast.success('Draft created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create draft: ' + error.message);
    },
  });
}

// Update a draft
export function useUpdateDraft() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, updates }: { id: string; updates: UpdateDraftInput }): Promise<AIAssistDraft> => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;

      const { data, error } = await supabase
        .from('ai_assist_drafts')
        .update(updates as Record<string, unknown>)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      // Log audit event for step change
      if (updates.current_step !== undefined) {
        await logAuditEvent(id, null, 'step_changed', userId, { step: updates.current_step });
      } else {
        await logAuditEvent(id, null, 'draft_updated', userId, { updates: updates as Record<string, unknown> });
      }

      return data as AIAssistDraft;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['ai-assist-drafts'] });
      queryClient.invalidateQueries({ queryKey: ['ai-assist-draft', data.id] });
      queryClient.invalidateQueries({ queryKey: ['ai-assist-draft', data.draft_key] });
    },
    onError: (error) => {
      toast.error('Failed to update draft: ' + error.message);
    },
  });
}

// Soft delete a draft (admin only)
export function useDeleteDraft() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (id: string): Promise<void> => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;

      // Soft delete
      const { error } = await supabase
        .from('ai_assist_drafts')
        .update({ deleted_at: new Date().toISOString() })
        .eq('id', id);

      if (error) throw error;

      // Log audit event
      await logAuditEvent(id, null, 'admin_deleted', userId, { deleted_at: new Date().toISOString() });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-assist-drafts'] });
      toast.success('Draft deleted successfully');
    },
    onError: (error) => {
      toast.error('Failed to delete draft: ' + error.message);
    },
  });
}

// Audit event logging
export type AuditEventType =
  | 'upload'
  | 'extract'
  | 'run_started'
  | 'run_completed'
  | 'content_changed'
  | 'compliance_noncompliant'
  | 'justification_recorded'
  | 'oq_answered'
  | 'br_linked'
  | 'epics_published'
  | 'export_pdf'
  | 'admin_deleted'
  | 'draft_created'
  | 'draft_updated'
  | 'step_changed';

export async function logAuditEvent(
  draftId: string,
  runId: string | null,
  eventType: AuditEventType,
  actorUserId: string | null | undefined,
  payloadJson: Record<string, unknown> = {}
) {
  const { error } = await supabase
    .from('ai_assist_audit_events')
    .insert({
      draft_id: draftId,
      run_id: runId,
      event_type: eventType,
      actor_user_id: actorUserId,
      payload_json: payloadJson as Json,
    });

  if (error) {
    console.error('Failed to log audit event:', error);
  }
}

// Fetch audit events for a draft
export function useAIAssistAuditEvents(draftId: string | undefined) {
  return useQuery({
    queryKey: ['ai-assist-audit-events', draftId],
    queryFn: async () => {
      if (!draftId) return [];

      const { data, error } = await supabase
        .from('ai_assist_audit_events')
        .select('*')
        .eq('draft_id', draftId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data;
    },
    enabled: !!draftId,
  });
}
