import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import type { Json } from '@/integrations/supabase/types';

export type DraftStatus = 'draft' | 'in_progress' | 'review' | 'approved' | 'published' | 'archived';
export type DraftLanguage = 'ar' | 'en' | 'mixed';
export type DraftDir = 'rtl' | 'ltr';
export type ComplianceVerdict = 'pass' | 'fail' | 'pending' | 'na' | null;

export interface AIAssistDraft {
  id: string;
  draft_key: string;
  title: string;
  language: DraftLanguage;
  dir: DraftDir;
  status: DraftStatus;
  current_step: number;
  step_data: Json;
  prompt_pack_version: string | null;
  sources_pack_version: string | null;
  compliance_verdict: ComplianceVerdict;
  quality_score: number | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface CreateDraftInput {
  title: string;
  language?: DraftLanguage;
  dir?: DraftDir;
}

export interface UpdateDraftInput {
  title?: string;
  language?: DraftLanguage;
  dir?: DraftDir;
  status?: DraftStatus;
  current_step?: number;
  step_data?: Json;
  prompt_pack_version?: string;
  sources_pack_version?: string;
  compliance_verdict?: ComplianceVerdict;
  quality_score?: number;
}

// Fetch all non-deleted drafts
export function useAIAssistDrafts() {
  return useQuery({
    queryKey: ['ai-assist-drafts'],
    queryFn: async (): Promise<AIAssistDraft[]> => {
      const { data, error } = await supabase
        .from('ai_assist_drafts')
        .select('*')
        .eq('is_deleted', false)
        .order('updated_at', { ascending: false });

      if (error) throw error;
      return data as AIAssistDraft[];
    },
  });
}

// Fetch a single draft by ID or draft_key
export function useAIAssistDraft(draftIdOrKey: string | undefined) {
  return useQuery({
    queryKey: ['ai-assist-draft', draftIdOrKey],
    queryFn: async (): Promise<AIAssistDraft | null> => {
      if (!draftIdOrKey) return null;

      // Try to find by id first, then by draft_key
      let query = supabase
        .from('ai_assist_drafts')
        .select('*')
        .eq('is_deleted', false);

      // Check if it looks like a UUID or a draft_key (AID-XXXX)
      if (draftIdOrKey.startsWith('AID-')) {
        query = query.eq('draft_key', draftIdOrKey);
      } else {
        query = query.eq('id', draftIdOrKey);
      }

      const { data, error } = await query.maybeSingle();
      if (error) throw error;
      return data as AIAssistDraft | null;
    },
    enabled: !!draftIdOrKey,
  });
}

// Create a new draft
export function useCreateDraft() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (input: CreateDraftInput): Promise<AIAssistDraft> => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;

      const { data, error } = await supabase
        .from('ai_assist_drafts')
        .insert({
          title: input.title,
          language: input.language || 'ar',
          dir: input.dir || 'rtl',
          created_by: userId,
          draft_key: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) throw error;

      // Log audit event
      await logAuditEvent(data.id, null, 'draft_created', userId, { title: input.title });

      return data as AIAssistDraft;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['ai-assist-drafts'] });
      toast.success('Draft created successfully');
    },
    onError: (error) => {
      toast.error('Failed to create draft: ' + error.message);
    },
  });
}

// Update a draft
export function useUpdateDraft() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, updates }: { id: string; updates: UpdateDraftInput }): Promise<AIAssistDraft> => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;

      const { data, error } = await supabase
        .from('ai_assist_drafts')
        .update(updates as Record<string, unknown>)
        .eq('id', id)
        .select()
        .single();

      if (error) throw error;

      // Log audit event for step change
      if (updates.current_step !== undefined) {
        await logAuditEvent(id, null, 'step_changed', userId, { step: updates.current_step });
      } else {
        await logAuditEvent(id, null, 'draft_updated', userId, { updates: updates as Record<string, unknown> });
      }

      return data as AIAssistDraft;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['ai-assist-drafts'] });
      queryClient.invalidateQueries({ queryKey: ['ai-assist-draft', data.id] });
      queryClient.invalidateQueries({ queryKey: ['ai-assist-draft', data.draft_key] });
    },
    onError: (error) => {
      toast.error('Failed to update draft: ' + error.message);
    },
  });
}

// Soft delete a draft with full audit trail
export interface DeleteDraftInput {
  id: string;
  draftKey: string;
  reason?: string;
}

export function useDeleteDraft() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, draftKey, reason }: DeleteDraftInput): Promise<{ id: string; draftKey: string }> => {
      const { data: userData } = await supabase.auth.getUser();
      const userId = userData.user?.id;
      const deletedAt = new Date().toISOString();

      // First check if draft is already deleted (bypass RLS filter by checking specific fields)
      const { data: existingDraft, error: checkError } = await supabase
        .from('ai_assist_drafts')
        .select('id, is_deleted, deleted_at')
        .eq('id', id)
        .maybeSingle();

      if (checkError) {
        console.error('[AI Assist] Delete failed - check error', { draft_id: id, draft_key: draftKey, error: checkError });
        throw new Error(`Failed to check draft status: ${checkError.message}`);
      }

      if (!existingDraft) {
        console.error('[AI Assist] Delete failed - draft not found', { draft_id: id, draft_key: draftKey });
        throw new Error('Draft not found');
      }

      if (existingDraft.is_deleted || existingDraft.deleted_at) {
        console.info('[AI Assist] Draft already deleted', { draft_id: id, draft_key: draftKey });
        throw new Error('Draft already deleted');
      }

      // Perform soft delete - set all soft delete fields
      const { error: updateError } = await supabase
        .from('ai_assist_drafts')
        .update({ 
          deleted_at: deletedAt,
          is_deleted: true,
          deleted_by: userId,
        })
        .eq('id', id);

      if (updateError) {
        console.error('[AI Assist] Delete failed', { draft_id: id, draft_key: draftKey, error: updateError });
        throw new Error(`Failed to delete draft: ${updateError.message}`);
      }

      // Log immutable audit event
      await logAuditEvent(id, null, 'draft_deleted', userId, { 
        draft_id: id,
        draft_key: draftKey,
        actor_user_id: userId,
        deleted_at: deletedAt,
        reason_optional: reason || null,
      });

      console.info('[AI Assist] Draft deleted successfully', { draft_id: id, draft_key: draftKey });
      return { id, draftKey };
    },
    onMutate: async ({ id }) => {
      // Cancel any outgoing refetches
      await queryClient.cancelQueries({ queryKey: ['ai-assist-drafts'] });
      
      // Snapshot the previous value
      const previousDrafts = queryClient.getQueryData<AIAssistDraft[]>(['ai-assist-drafts']);
      
      // Optimistically remove the draft from the list
      if (previousDrafts) {
        queryClient.setQueryData<AIAssistDraft[]>(
          ['ai-assist-drafts'],
          previousDrafts.filter(draft => draft.id !== id)
        );
      }
      
      return { previousDrafts };
    },
    onSuccess: (data) => {
      // Invalidate to ensure consistency
      queryClient.invalidateQueries({ queryKey: ['ai-assist-drafts'] });
      queryClient.invalidateQueries({ queryKey: ['ai-assist-draft', data.id] });
      queryClient.invalidateQueries({ queryKey: ['ai-assist-draft', data.draftKey] });
      toast.success('Draft deleted');
    },
    onError: (error, variables, context) => {
      // Rollback on error
      if (context?.previousDrafts) {
        queryClient.setQueryData(['ai-assist-drafts'], context.previousDrafts);
      }
      const message = error instanceof Error ? error.message : 'Unknown error';
      console.error('[AI Assist] Delete failed', { draft_id: variables.id, draft_key: variables.draftKey, error: message });
      toast.error(`Delete failed: ${message}`);
    },
  });
}

// Audit event logging - all required events per JOB-139
export type AuditEventType =
  | 'draft_created'
  | 'draft_opened'
  | 'draft_updated'
  | 'draft_deleted'
  | 'document_uploaded'
  | 'document_replaced'
  | 'extraction_started'
  | 'extraction_completed'
  | 'extraction_reviewed'
  | 'quality_warn_acknowledged'
  | 'step_completed'
  | 'state_corrected'
  | 'continue_blocked'
  | 'run_started'
  | 'run_completed'
  | 'content_changed'
  | 'compliance_noncompliant'
  | 'justification_recorded'
  | 'oq_answered'
  | 'br_linked'
  | 'epics_published'
  | 'export_pdf'
  | 'admin_deleted'
  | 'step_changed'
  // Legacy - keep for backwards compat
  | 'upload'
  | 'extract';

export async function logAuditEvent(
  draftId: string,
  runId: string | null,
  eventType: AuditEventType,
  actorUserId: string | null | undefined,
  payloadJson: Record<string, unknown> = {}
) {
  const { error } = await supabase
    .from('ai_assist_audit_events')
    .insert({
      draft_id: draftId,
      run_id: runId,
      event_type: eventType,
      actor_user_id: actorUserId,
      payload_json: payloadJson as Json,
    });

  if (error) {
    console.error('Failed to log audit event:', error);
  }
}

// Fetch audit events for a draft
export function useAIAssistAuditEvents(draftId: string | undefined) {
  return useQuery({
    queryKey: ['ai-assist-audit-events', draftId],
    queryFn: async () => {
      if (!draftId) return [];

      const { data, error } = await supabase
        .from('ai_assist_audit_events')
        .select('*')
        .eq('draft_id', draftId)
        .order('created_at', { ascending: false });

      if (error) throw error;
      return data;
    },
    enabled: !!draftId,
  });
}
