import { useQuery } from '@tanstack/react-query';
import type { Initiative } from '@/types/initiative';

/**
 * Mock data hook — returns the same 18-initiative dataset as the DB seed.
 * Use this as a fallback when Supabase auth is not yet configured.
 */

const MOCK_INITIATIVES: Initiative[] = [
  { id: '1', initiative_key: 'MIM-001', title: 'Digital Transformation Phase 2', description: 'Phase 2 of the enterprise-wide digital transformation initiative focusing on customer-facing digital channels, process automation, and data-driven decision making.', status: 'in_progress', assignee_id: null, assignee_name: 'Sarah Chen', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Ahmad Al-Rashid', reporter_id: null, department_id: null, department_name: 'Digital Transformation', target_quarter: 'Q1 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-03-31', progress: 72, sort_order: 1, risk_count: 2, is_archived: false, is_favorited: true, score_strategic_alignment: 4.5, score_business_impact: 5.0, score_time_urgency: 4.0, score_resource_feasibility: 4.5, computed_score: 4.5, created_at: '2025-01-15T00:00:00Z', updated_at: '2026-02-10T00:00:00Z' },
  { id: '2', initiative_key: 'MIM-002', title: 'Core Banking System Modernization', description: 'Modernization of the core banking platform to support real-time processing and modern API integrations.', status: 'in_progress', assignee_id: null, assignee_name: 'Mohammed Al-Sayed', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Khalid Ibrahim', reporter_id: null, department_id: null, department_name: 'IT Operations', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-06-30', progress: 45, sort_order: 2, risk_count: 3, is_archived: false, is_favorited: false, score_strategic_alignment: 4.8, score_business_impact: 5.0, score_time_urgency: 4.5, score_resource_feasibility: 4.9, computed_score: 4.8, created_at: '2025-02-01T00:00:00Z', updated_at: '2026-02-08T00:00:00Z' },
  { id: '3', initiative_key: 'MIM-003', title: 'Customer Experience Platform', description: 'End-to-end customer experience platform covering journey mapping, feedback collection, and NPS tracking.', status: 'approved', assignee_id: null, assignee_name: 'Fatima Al-Zahra', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Nora Hassan', reporter_id: null, department_id: null, department_name: 'Customer Experience', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-06-15', progress: 15, sort_order: 3, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 4.0, score_business_impact: 4.5, score_time_urgency: 4.0, score_resource_feasibility: 4.3, computed_score: 4.2, created_at: '2025-03-01T00:00:00Z', updated_at: '2026-02-05T00:00:00Z' },
  { id: '4', initiative_key: 'MIM-004', title: 'Data Analytics & BI Dashboard', description: 'Enterprise BI dashboard for real-time analytics and executive reporting.', status: 'in_progress', assignee_id: null, assignee_name: 'Omar Farooq', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Layla Ahmed', reporter_id: null, department_id: null, department_name: 'Data & Analytics', target_quarter: 'Q1 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-03-15', progress: 88, sort_order: 4, risk_count: 1, is_archived: false, is_favorited: true, score_strategic_alignment: 3.5, score_business_impact: 4.0, score_time_urgency: 4.0, score_resource_feasibility: 3.7, computed_score: 3.8, created_at: '2025-02-15T00:00:00Z', updated_at: '2026-02-12T00:00:00Z' },
  { id: '5', initiative_key: 'MIM-005', title: 'Mobile App Redesign', description: 'Complete redesign of the mobile banking application with modern UX patterns.', status: 'under_review', assignee_id: null, assignee_name: null, assignee_avatar: null, business_owner_id: null, business_owner_name: 'Ahmad Al-Rashid', reporter_id: null, department_id: null, department_name: 'Digital Transformation', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-05-30', progress: 0, sort_order: 5, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 3.5, score_business_impact: 3.8, score_time_urgency: 3.0, score_resource_feasibility: 3.7, computed_score: 3.5, created_at: '2025-04-01T00:00:00Z', updated_at: '2026-01-20T00:00:00Z' },
  { id: '6', initiative_key: 'MIM-006', title: 'API Gateway Implementation', description: 'Implementation of centralized API gateway for service mesh architecture.', status: 'in_progress', assignee_id: null, assignee_name: 'Yusuf Ali', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Khalid Ibrahim', reporter_id: null, department_id: null, department_name: 'IT Operations', target_quarter: 'Q1 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-02-28', progress: 95, sort_order: 6, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 4.0, score_business_impact: 4.0, score_time_urgency: 4.0, score_resource_feasibility: 4.0, computed_score: 4.0, created_at: '2025-01-20T00:00:00Z', updated_at: '2026-02-14T00:00:00Z' },
  { id: '7', initiative_key: 'MIM-007', title: 'Employee Self-Service Portal', description: 'Self-service portal for employees to manage HR requests, leave, and benefits.', status: 'new_demand', assignee_id: null, assignee_name: null, assignee_avatar: null, business_owner_id: null, business_owner_name: 'Amira Khalil', reporter_id: null, department_id: null, department_name: 'Human Resources', target_quarter: 'Q3 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-09-30', progress: 0, sort_order: 7, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: null, score_business_impact: null, score_time_urgency: null, score_resource_feasibility: null, computed_score: null, created_at: '2025-05-01T00:00:00Z', updated_at: '2025-05-01T00:00:00Z' },
  { id: '8', initiative_key: 'MIM-008', title: 'Compliance Reporting Automation', description: 'Automated compliance reporting for regulatory requirements.', status: 'approved', assignee_id: null, assignee_name: 'Hassan Mahmoud', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Tariq Nasser', reporter_id: null, department_id: null, department_name: 'Risk & Compliance', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-07-15', progress: 10, sort_order: 8, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 3.0, score_business_impact: 3.5, score_time_urgency: 3.0, score_resource_feasibility: 3.3, computed_score: 3.2, created_at: '2025-03-15T00:00:00Z', updated_at: '2026-01-10T00:00:00Z' },
  { id: '9', initiative_key: 'MIM-009', title: 'Cloud Migration Strategy', description: 'Enterprise cloud migration strategy covering infrastructure, applications, and data workloads.', status: 'in_progress', assignee_id: null, assignee_name: 'Rania Othman', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Khalid Ibrahim', reporter_id: null, department_id: null, department_name: 'IT Operations', target_quarter: 'Q1 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-04-30', progress: 60, sort_order: 9, risk_count: 1, is_archived: false, is_favorited: false, score_strategic_alignment: 4.8, score_business_impact: 4.5, score_time_urgency: 4.5, score_resource_feasibility: 4.6, computed_score: 4.6, created_at: '2025-01-10T00:00:00Z', updated_at: '2026-02-11T00:00:00Z' },
  { id: '10', initiative_key: 'MIM-010', title: 'Vendor Management System', description: 'Centralized vendor management and procurement optimization platform.', status: 'on_hold', assignee_id: null, assignee_name: 'Aisha Bakr', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Salman Qureshi', reporter_id: null, department_id: null, department_name: 'Procurement', target_quarter: 'Q3 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-10-31', progress: 20, sort_order: 10, risk_count: 1, is_archived: false, is_favorited: false, score_strategic_alignment: 2.5, score_business_impact: 3.0, score_time_urgency: 2.5, score_resource_feasibility: 3.2, computed_score: 2.8, created_at: '2025-04-15T00:00:00Z', updated_at: '2026-01-05T00:00:00Z' },
  { id: '11', initiative_key: 'MIM-011', title: 'Security Operations Center (SOC)', description: '24/7 security operations center with SIEM integration and threat intelligence.', status: 'in_progress', assignee_id: null, assignee_name: 'Zaid Al-Harbi', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Mansour Faisal', reporter_id: null, department_id: null, department_name: 'Cybersecurity', target_quarter: 'Q1 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-03-31', progress: 55, sort_order: 11, risk_count: 2, is_archived: false, is_favorited: false, score_strategic_alignment: 4.5, score_business_impact: 4.0, score_time_urgency: 4.5, score_resource_feasibility: 4.2, computed_score: 4.3, created_at: '2025-02-20T00:00:00Z', updated_at: '2026-02-09T00:00:00Z' },
  { id: '12', initiative_key: 'MIM-012', title: 'Payment Gateway Integration', description: 'Integration with national payment gateway for real-time transaction processing.', status: 'delivered', assignee_id: null, assignee_name: 'Sarah Chen', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Ahmad Al-Rashid', reporter_id: null, department_id: null, department_name: 'Digital Transformation', target_quarter: 'Q4 2025', business_ask_date: null, kickoff_date: null, target_complete: '2025-12-15', progress: 100, sort_order: 12, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 3.8, score_business_impact: 4.0, score_time_urgency: 4.0, score_resource_feasibility: 3.8, computed_score: 3.9, created_at: '2025-01-05T00:00:00Z', updated_at: '2025-12-15T00:00:00Z' },
  { id: '13', initiative_key: 'MIM-013', title: 'HR Performance Management System', description: 'Performance management system with goal tracking, reviews, and analytics.', status: 'under_review', assignee_id: null, assignee_name: null, assignee_avatar: null, business_owner_id: null, business_owner_name: 'Amira Khalil', reporter_id: null, department_id: null, department_name: 'Human Resources', target_quarter: 'Q3 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-08-31', progress: 0, sort_order: 13, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 2.5, score_business_impact: 2.5, score_time_urgency: 2.5, score_resource_feasibility: 2.5, computed_score: 2.5, created_at: '2025-05-10T00:00:00Z', updated_at: '2025-12-20T00:00:00Z' },
  { id: '14', initiative_key: 'MIM-014', title: 'Supply Chain Optimization', description: 'Supply chain optimization using AI-driven demand forecasting.', status: 'new_demand', assignee_id: null, assignee_name: null, assignee_avatar: null, business_owner_id: null, business_owner_name: 'Waleed Hamza', reporter_id: null, department_id: null, department_name: 'Operations', target_quarter: 'Q3 2026', business_ask_date: null, kickoff_date: null, target_complete: null, progress: 0, sort_order: 14, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: null, score_business_impact: null, score_time_urgency: null, score_resource_feasibility: null, computed_score: null, created_at: '2025-06-01T00:00:00Z', updated_at: '2025-06-01T00:00:00Z' },
  { id: '15', initiative_key: 'MIM-015', title: 'Customer 360 View', description: 'Unified customer profile aggregating data from all touchpoints.', status: 'approved', assignee_id: null, assignee_name: 'Lina Saeed', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Nora Hassan', reporter_id: null, department_id: null, department_name: 'Customer Experience', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-06-30', progress: 5, sort_order: 15, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 4.0, score_business_impact: 4.2, score_time_urgency: 4.0, score_resource_feasibility: 4.2, computed_score: 4.1, created_at: '2025-03-20T00:00:00Z', updated_at: '2026-01-15T00:00:00Z' },
  { id: '16', initiative_key: 'MIM-016', title: 'DevOps Pipeline Automation', description: 'CI/CD pipeline automation with automated testing and deployment.', status: 'in_progress', assignee_id: null, assignee_name: 'Karim Nassar', assignee_avatar: null, business_owner_id: null, business_owner_name: 'Khalid Ibrahim', reporter_id: null, department_id: null, department_name: 'IT Operations', target_quarter: 'Q1 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-02-15', progress: 82, sort_order: 16, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 3.5, score_business_impact: 3.8, score_time_urgency: 3.5, score_resource_feasibility: 3.6, computed_score: 3.6, created_at: '2025-01-25T00:00:00Z', updated_at: '2026-02-13T00:00:00Z' },
  { id: '17', initiative_key: 'MIM-017', title: 'Enterprise Content Management', description: 'Enterprise content management system — cancelled due to vendor issues.', status: 'cancelled', assignee_id: null, assignee_name: null, assignee_avatar: null, business_owner_id: null, business_owner_name: 'Khalid Ibrahim', reporter_id: null, department_id: null, department_name: 'IT Operations', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: null, progress: 0, sort_order: 17, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 1.5, score_business_impact: 2.0, score_time_urgency: 1.5, score_resource_feasibility: 2.2, computed_score: 1.8, created_at: '2025-04-10T00:00:00Z', updated_at: '2025-11-30T00:00:00Z' },
  { id: '18', initiative_key: 'MIM-018', title: 'Real-time Fraud Detection System', description: 'Real-time fraud detection using machine learning and behavioral analytics.', status: 'under_review', assignee_id: null, assignee_name: null, assignee_avatar: null, business_owner_id: null, business_owner_name: 'Mansour Faisal', reporter_id: null, department_id: null, department_name: 'Cybersecurity', target_quarter: 'Q2 2026', business_ask_date: null, kickoff_date: null, target_complete: '2026-07-31', progress: 0, sort_order: 18, risk_count: 0, is_archived: false, is_favorited: false, score_strategic_alignment: 3.5, score_business_impact: 3.5, score_time_urgency: 3.0, score_resource_feasibility: 3.6, computed_score: 3.4, created_at: '2025-05-15T00:00:00Z', updated_at: '2026-01-08T00:00:00Z' },
];

/**
 * Mock hook — returns the same Initiative[] shape as useInitiatives but from hardcoded data.
 * Default data source until Supabase auth is fully wired.
 */
export function useInitiativesMock() {
  return useQuery({
    queryKey: ['ph-initiatives-mock'],
    queryFn: async () => {
      // Simulate network delay
      await new Promise(resolve => setTimeout(resolve, 300));
      return { data: MOCK_INITIATIVES, count: MOCK_INITIATIVES.length };
    },
    staleTime: Infinity,
  });
}

export default useInitiativesMock;
