/**
 * ads-violations.generated.ts — AUTO-GENERATED by scripts/scan-ads-violations.ts.
 *
 * Do NOT edit by hand. Run `npm run scan:ads-violations` to regenerate
 * after fixing or introducing a violation.
 *
 * Captured: 2026-07-09T11:58:07.752Z
 * Total: 15 (P0: 5, P1: 2, P2: 8)
 */

export type AdsViolationCategory =
  | 'hand-rolled-dropdown'
  | 'banned-import'
  | 'deprecated-shim'
  | 'lozenge-duplicate';

export type AdsViolationSeverity = 'P0' | 'P1' | 'P2';

export interface AdsViolation {
  id: string;
  category: AdsViolationCategory;
  severity: AdsViolationSeverity;
  /** Repo-relative file path. */
  file: string;
  line: number;
  /** Single-line excerpt of the offending source. */
  excerpt: string;
  /** Human-readable rule statement. */
  rule: string;
  /** Suggested fix. */
  suggestion: string;
  /** CLAUDE.md lesson date the rule traces back to. */
  claudeAnchor?: string;
}

export const adsViolations: AdsViolation[] = [
  {
    "id": "banned:src/stories/enterprise/CatalystViewBase.stories.tsx:12",
    "category": "banned-import",
    "severity": "P0",
    "file": "src/stories/enterprise/CatalystViewBase.stories.tsx",
    "line": 12,
    "excerpt": "import { CatalystAssessmentFeatureField } from '@/components/catalyst-detail-views/shared/sections/CatalystAssessmentFeatureField';",
    "rule": "Assessment Feature field is permanently banned.",
    "suggestion": "REMOVE this import. See CLAUDE.md 2026-05-07.",
    "claudeAnchor": "2026-05-07"
  },
  {
    "id": "banned:src/stories/enterprise/CatalystViewBase.stories.tsx:13",
    "category": "banned-import",
    "severity": "P0",
    "file": "src/stories/enterprise/CatalystViewBase.stories.tsx",
    "line": 13,
    "excerpt": "import { CatalystMdtRefField } from '@/components/catalyst-detail-views/shared/sections/CatalystMdtRefField';",
    "rule": "MDT Ref field is permanently banned.",
    "suggestion": "REMOVE this import. See CLAUDE.md 2026-05-05.",
    "claudeAnchor": "2026-05-05"
  },
  {
    "id": "dropdown:src/components/catalyst-detail-views/shared/sections/Description/_components/CellChevronHandles/CellChevronHandles.tsx:61",
    "category": "hand-rolled-dropdown",
    "severity": "P0",
    "file": "src/components/catalyst-detail-views/shared/sections/Description/_components/CellChevronHandles/CellChevronHandles.tsx",
    "line": 61,
    "excerpt": "const [menu, setMenu] = useState<OpenMenu | null>(null);",
    "rule": "Hand-rolled menu/popover state combined with an outside-click listener (mousedown or capture-phase click).",
    "suggestion": "Replace with @atlaskit/dropdown-menu (DropdownMenu + DropdownItem + DropdownItemGroup). See CLAUDE.md 2026-05-10.",
    "claudeAnchor": "2026-05-10"
  },
  {
    "id": "dropdown:src/components/catalyst-detail-views/shared/sections/Description/_components/TableInteractions/TableInteractions.tsx:87",
    "category": "hand-rolled-dropdown",
    "severity": "P0",
    "file": "src/components/catalyst-detail-views/shared/sections/Description/_components/TableInteractions/TableInteractions.tsx",
    "line": 87,
    "excerpt": "const [activeMenu, setActiveMenu] = useState<ActiveMenu | null>(null);",
    "rule": "Hand-rolled menu/popover state combined with an outside-click listener (mousedown or capture-phase click).",
    "suggestion": "Replace with @atlaskit/dropdown-menu (DropdownMenu + DropdownItem + DropdownItemGroup). See CLAUDE.md 2026-05-10.",
    "claudeAnchor": "2026-05-10"
  },
  {
    "id": "dropdown:src/components/hierarchy/HierarchyContextMenu.tsx:47",
    "category": "hand-rolled-dropdown",
    "severity": "P0",
    "file": "src/components/hierarchy/HierarchyContextMenu.tsx",
    "line": 47,
    "excerpt": "const [subMenu, setSubMenu] = useState<SubMenu>(null);",
    "rule": "Hand-rolled menu/popover state combined with an outside-click listener (mousedown or capture-phase click).",
    "suggestion": "Replace with @atlaskit/dropdown-menu (DropdownMenu + DropdownItem + DropdownItemGroup). See CLAUDE.md 2026-05-10.",
    "claudeAnchor": "2026-05-10"
  },
  {
    "id": "deprecated:src/modules/project-work-hub/pages/StoryBacklogPage.tsx:39",
    "category": "deprecated-shim",
    "severity": "P1",
    "file": "src/modules/project-work-hub/pages/StoryBacklogPage.tsx",
    "line": 39,
    "excerpt": "import { DynamicTable, useTablePersistence } from '@/components/shared/dynamic-table';",
    "rule": "Importing the deprecated dynamic-table.",
    "suggestion": "Migrate to JiraTable (@/components/shared/JiraTable)."
  },
  {
    "id": "deprecated:src/modules/project-work-hub/pages/StoryBacklogPage.tsx:40",
    "category": "deprecated-shim",
    "severity": "P1",
    "file": "src/modules/project-work-hub/pages/StoryBacklogPage.tsx",
    "line": 40,
    "excerpt": "import type { DynamicTableColumn, DynamicTableRowGroup } from '@/components/shared/dynamic-table';",
    "rule": "Importing the deprecated dynamic-table.",
    "suggestion": "Migrate to JiraTable (@/components/shared/JiraTable)."
  },
  {
    "id": "lozenge:src/components/releasehub/shared/ReleaseOpsLozenges.tsx:8",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/components/releasehub/shared/ReleaseOpsLozenges.tsx",
    "line": 8,
    "excerpt": "import { Lozenge, type LozengeAppearance } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/components/releasehub/signoff/SignoffDependencyGraph.tsx:14",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/components/releasehub/signoff/SignoffDependencyGraph.tsx",
    "line": 14,
    "excerpt": "import { Lozenge, type LozengeAppearance } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/pages/releasehub/ChangeDetailPage.tsx:19",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/pages/releasehub/ChangeDetailPage.tsx",
    "line": 19,
    "excerpt": "import { Lozenge } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/pages/releasehub/FreezeWindowsPage.tsx:19",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/pages/releasehub/FreezeWindowsPage.tsx",
    "line": 19,
    "excerpt": "import { Lozenge } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/pages/releasehub/ProductionEventReplayPage.tsx:17",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/pages/releasehub/ProductionEventReplayPage.tsx",
    "line": 17,
    "excerpt": "import { Lozenge } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/pages/releasehub/ReleaseDetailPage.tsx:24",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/pages/releasehub/ReleaseDetailPage.tsx",
    "line": 24,
    "excerpt": "import { Lozenge } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/pages/releasehub/SignOffQueuePage.tsx:20",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/pages/releasehub/SignOffQueuePage.tsx",
    "line": 20,
    "excerpt": "import { Lozenge } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  },
  {
    "id": "lozenge:src/pages/releasehub/SopTemplatesPage.tsx:15",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/pages/releasehub/SopTemplatesPage.tsx",
    "line": 15,
    "excerpt": "import { Lozenge } from '@/components/ads/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  }
];

export const adsViolationsStats = {
  total: 15,
  byCategory: {"banned-import":2,"hand-rolled-dropdown":3,"deprecated-shim":2,"lozenge-duplicate":8},
  bySeverity: {"P0":5,"P1":2,"P2":8},
  generatedAt: '2026-07-09T11:58:07.752Z',
};
