/**
 * ads-violations.generated.ts — AUTO-GENERATED by scripts/scan-ads-violations.ts.
 *
 * Do NOT edit by hand. Run `npm run scan:ads-violations` to regenerate
 * after fixing or introducing a violation.
 *
 * Captured: 2026-05-17T15:07:50.203Z
 * Total: 6 (P0: 3, P1: 2, P2: 1)
 */

export type AdsViolationCategory =
  | 'hand-rolled-dropdown'
  | 'banned-import'
  | 'deprecated-shim'
  | 'lozenge-duplicate';

export type AdsViolationSeverity = 'P0' | 'P1' | 'P2';

export interface AdsViolation {
  id: string;
  category: AdsViolationCategory;
  severity: AdsViolationSeverity;
  /** Repo-relative file path. */
  file: string;
  line: number;
  /** Single-line excerpt of the offending source. */
  excerpt: string;
  /** Human-readable rule statement. */
  rule: string;
  /** Suggested fix. */
  suggestion: string;
  /** CLAUDE.md lesson date the rule traces back to. */
  claudeAnchor?: string;
}

export const adsViolations: AdsViolation[] = [
  {
    "id": "dropdown:src/components/hierarchy/HierarchyContextMenu.tsx:47",
    "category": "hand-rolled-dropdown",
    "severity": "P0",
    "file": "src/components/hierarchy/HierarchyContextMenu.tsx",
    "line": 47,
    "excerpt": "const [subMenu, setSubMenu] = useState<SubMenu>(null);",
    "rule": "Hand-rolled menu/popover state combined with an outside-click listener (mousedown or capture-phase click).",
    "suggestion": "Replace with @atlaskit/dropdown-menu (DropdownMenu + DropdownItem + DropdownItemGroup). See CLAUDE.md 2026-05-10.",
    "claudeAnchor": "2026-05-10"
  },
  {
    "id": "dropdown:src/components/testhub/FolderPanel.tsx:77",
    "category": "hand-rolled-dropdown",
    "severity": "P0",
    "file": "src/components/testhub/FolderPanel.tsx",
    "line": 77,
    "excerpt": "const [folderContextMenu, setFolderContextMenu] = useState<FolderContextMenuState | null>(null);",
    "rule": "Hand-rolled menu/popover state combined with an outside-click listener (mousedown or capture-phase click).",
    "suggestion": "Replace with @atlaskit/dropdown-menu (DropdownMenu + DropdownItem + DropdownItemGroup). See CLAUDE.md 2026-05-10.",
    "claudeAnchor": "2026-05-10"
  },
  {
    "id": "dropdown:src/pages/testhub/TestRepositoryPage.tsx:129",
    "category": "hand-rolled-dropdown",
    "severity": "P0",
    "file": "src/pages/testhub/TestRepositoryPage.tsx",
    "line": 129,
    "excerpt": "const [contextMenu, setContextMenu] = useState<ContextMenuState | null>(null);",
    "rule": "Hand-rolled menu/popover state combined with an outside-click listener (mousedown or capture-phase click).",
    "suggestion": "Replace with @atlaskit/dropdown-menu (DropdownMenu + DropdownItem + DropdownItemGroup). See CLAUDE.md 2026-05-10.",
    "claudeAnchor": "2026-05-10"
  },
  {
    "id": "deprecated:src/modules/project-work-hub/pages/StoryBacklogPage.tsx:39",
    "category": "deprecated-shim",
    "severity": "P1",
    "file": "src/modules/project-work-hub/pages/StoryBacklogPage.tsx",
    "line": 39,
    "excerpt": "import { DynamicTable, useTablePersistence } from '@/components/shared/dynamic-table';",
    "rule": "Importing the deprecated dynamic-table.",
    "suggestion": "Migrate to JiraTable (@/components/shared/JiraTable)."
  },
  {
    "id": "deprecated:src/modules/project-work-hub/pages/StoryBacklogPage.tsx:40",
    "category": "deprecated-shim",
    "severity": "P1",
    "file": "src/modules/project-work-hub/pages/StoryBacklogPage.tsx",
    "line": 40,
    "excerpt": "import type { DynamicTableColumn, DynamicTableRowGroup } from '@/components/shared/dynamic-table';",
    "rule": "Importing the deprecated dynamic-table.",
    "suggestion": "Migrate to JiraTable (@/components/shared/JiraTable)."
  },
  {
    "id": "lozenge:src/components/catalyst-ds/activity/ActivityItem.tsx:7",
    "category": "lozenge-duplicate",
    "severity": "P2",
    "file": "src/components/catalyst-ds/activity/ActivityItem.tsx",
    "line": 7,
    "excerpt": "import { Lozenge } from '../status/Lozenge';",
    "rule": "Importing a Lozenge from a non-canonical path.",
    "suggestion": "Import from @atlaskit/lozenge (canonical primitive)."
  }
];

export const adsViolationsStats = {
  total: 6,
  byCategory: {"hand-rolled-dropdown":3,"deprecated-shim":2,"lozenge-duplicate":1},
  bySeverity: {"P0":3,"P1":2,"P2":1},
  generatedAt: '2026-05-17T15:07:50.204Z',
};
