-- ============================================================================
-- STRATA Execution — Project Status Health & Forecast Date Calculation.
-- CAT-STRATA-20260705-001 (continuation, session 010).
--
-- Additive-only. Adds the milestone-derived baseline/variance/forecast fields
-- to strata_project_cards (rule 12 of the governing instructions). The
-- pre-existing project-level `baseline_start`/`baseline_end`/`forecast_end`
-- columns are left untouched (forecast_end remains the "submitted forecast"
-- source per rule 7; project-level baseline_start/end stay as whatever a
-- manual entry or Jira/import wrote, but rule 1 forbids using them for this
-- calculation — the new calc_baseline_* columns are the only inputs the
-- health engine reads).
-- ============================================================================

ALTER TABLE public.strata_project_cards
  ADD COLUMN IF NOT EXISTS calc_baseline_start date,
  ADD COLUMN IF NOT EXISTS calc_baseline_end date,
  ADD COLUMN IF NOT EXISTS baseline_progress_pct numeric(6,2),
  ADD COLUMN IF NOT EXISTS variance_pct numeric(6,2),
  ADD COLUMN IF NOT EXISTS system_forecast_end date,
  ADD COLUMN IF NOT EXISTS final_forecast_end date,
  ADD COLUMN IF NOT EXISTS forecast_variance_days integer,
  ADD COLUMN IF NOT EXISTS calculated_health text,
  ADD COLUMN IF NOT EXISTS health_reason text;

COMMENT ON COLUMN public.strata_project_cards.calc_baseline_start IS
  'Project baseline start derived as MIN(strata_milestones.baseline_start) — never the project-level baseline_start column. Written exclusively by strata_calc_execution_progress().';
COMMENT ON COLUMN public.strata_project_cards.calc_baseline_end IS
  'Project baseline end derived as MAX(strata_milestones.baseline_end) — never the project-level baseline_end column. Written exclusively by strata_calc_execution_progress().';
COMMENT ON COLUMN public.strata_project_cards.baseline_progress_pct IS
  'Planned % complete today per the milestone-derived baseline window (0 before start, elapsed/duration inside the window, 100 after end). NULL = Not Available.';
COMMENT ON COLUMN public.strata_project_cards.variance_pct IS
  'baseline_progress_pct - actual_progress. Positive = behind schedule, negative = ahead.';
COMMENT ON COLUMN public.strata_project_cards.system_forecast_end IS
  'Earned-schedule forecast: baseline end + (today - the baseline-equivalent date at which the planned curve reaches today''s actual progress). Never the crude variance% × duration shortcut.';
COMMENT ON COLUMN public.strata_project_cards.final_forecast_end IS
  'Later of system_forecast_end and the submitted forecast (existing forecast_end column), or whichever exists, or NULL.';
COMMENT ON COLUMN public.strata_project_cards.forecast_variance_days IS
  'final_forecast_end - calc_baseline_end, in days.';
COMMENT ON COLUMN public.strata_project_cards.calculated_health IS
  'Fixed server-calculated enum: on_hold | not_available | not_started | major_delay | minor_delay | on_track. Never manually settable — written exclusively by strata_calc_execution_progress(). Deliberately bypasses governed strata_threshold_schemes bands for this one metric (see D-022) because the owner-specified rule set uses fixed 10%/20%/30-day thresholds, not org-configurable bands.';
COMMENT ON COLUMN public.strata_project_cards.health_reason IS
  'Human-readable reason for calculated_health, generated by the same calculation, never freeform-editable.';

ALTER TABLE public.strata_project_cards
  ADD CONSTRAINT strata_project_cards_calculated_health_check
  CHECK (calculated_health IS NULL OR calculated_health IN
    ('on_hold','not_available','not_started','major_delay','minor_delay','on_track'));
