/**
 * RTM Mock Data Generator
 */
import type {
  RTMMetrics,
  RequirementTreeNode,
  RequirementTableRow,
  TestLink,
  TestExecutionStatus,
  RequirementType,
  Priority,
  CoverageStatus,
} from '../types';

const generateTestLinks = (count: number, statuses: TestExecutionStatus[]): TestLink[] => {
  return Array.from({ length: count }, (_, i) => ({
    testCaseId: `tc-${Math.random().toString(36).substr(2, 9)}`,
    testCaseKey: `TC-${1000 + Math.floor(Math.random() * 500)}`,
    testCaseTitle: `Test Case ${i + 1}`,
    lastExecutionId: `exec-${Math.random().toString(36).substr(2, 9)}`,
    lastExecutionStatus: statuses[i % statuses.length],
    lastExecutedAt: new Date(Date.now() - Math.random() * 7 * 24 * 60 * 60 * 1000).toISOString(),
    lastExecutionDuration: Math.floor(Math.random() * 300) + 30,
    linkedAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString(),
    linkedBy: 'QA Team',
  }));
};

const getCoverageStatus = (tests: TestLink[]): CoverageStatus => {
  if (tests.length === 0) return 'gap';
  const passed = tests.filter(t => t.lastExecutionStatus === 'passed').length;
  if (passed === tests.length) return 'covered';
  return 'partial';
};

const getCoveragePercentage = (tests: TestLink[]): number => {
  if (tests.length === 0) return 0;
  const passed = tests.filter(t => t.lastExecutionStatus === 'passed').length;
  return Math.round((passed / tests.length) * 100);
};

export const generateMockData = () => {
  // Generate table data
  const tableData: RequirementTableRow[] = [
    // Epic 1 - Payment Processing
    {
      id: 'epic-1',
      key: 'EPIC-101',
      title: 'Payment Processing Module',
      type: 'epic',
      priority: 'critical',
      linkedTests: generateTestLinks(8, ['passed', 'passed', 'passed', 'passed', 'passed', 'failed', 'passed', 'passed']),
      coveragePercentage: 87,
      coverageStatus: 'partial',
      coverageDetail: { passed: 7, failed: 1, blocked: 0, notRun: 0 },
    },
    {
      id: 'feat-1',
      key: 'FEAT-201',
      title: 'Credit Card Integration',
      type: 'feature',
      priority: 'critical',
      linkedTests: generateTestLinks(5, ['passed', 'passed', 'passed', 'passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 5, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'story-1',
      key: 'STORY-301',
      title: 'Visa/Mastercard Support',
      type: 'story',
      priority: 'high',
      linkedTests: generateTestLinks(3, ['passed', 'passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 3, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-1',
      key: 'REQ-401',
      title: 'Card number validation with Luhn algorithm',
      type: 'requirement',
      priority: 'critical',
      linkedTests: generateTestLinks(2, ['passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 2, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-2',
      key: 'REQ-402',
      title: 'CVV encryption at rest',
      type: 'requirement',
      priority: 'critical',
      linkedTests: generateTestLinks(3, ['passed', 'passed', 'failed']),
      coveragePercentage: 67,
      coverageStatus: 'partial',
      coverageDetail: { passed: 2, failed: 1, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-3',
      key: 'REQ-403',
      title: 'Expiry date format MM/YY',
      type: 'requirement',
      priority: 'medium',
      linkedTests: generateTestLinks(1, ['passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 1, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'feat-2',
      key: 'FEAT-202',
      title: 'SADAD Integration',
      type: 'feature',
      priority: 'high',
      linkedTests: generateTestLinks(4, ['passed', 'passed', 'blocked', 'not_run']),
      coveragePercentage: 50,
      coverageStatus: 'partial',
      coverageDetail: { passed: 2, failed: 0, blocked: 1, notRun: 1 },
    },
    {
      id: 'story-2',
      key: 'STORY-302',
      title: 'Bill Payment Flow',
      type: 'story',
      priority: 'high',
      linkedTests: generateTestLinks(2, ['passed', 'blocked']),
      coveragePercentage: 50,
      coverageStatus: 'partial',
      coverageDetail: { passed: 1, failed: 0, blocked: 1, notRun: 0 },
    },
    {
      id: 'req-4',
      key: 'REQ-404',
      title: 'SADAD OTP verification',
      type: 'requirement',
      priority: 'high',
      linkedTests: [],
      coveragePercentage: 0,
      coverageStatus: 'gap',
      coverageDetail: { passed: 0, failed: 0, blocked: 0, notRun: 0 },
    },
    // Epic 2 - User Management
    {
      id: 'epic-2',
      key: 'EPIC-102',
      title: 'User Management System',
      type: 'epic',
      priority: 'high',
      linkedTests: generateTestLinks(6, ['passed', 'passed', 'passed', 'passed', 'failed', 'not_run']),
      coveragePercentage: 67,
      coverageStatus: 'partial',
      coverageDetail: { passed: 4, failed: 1, blocked: 0, notRun: 1 },
    },
    {
      id: 'feat-3',
      key: 'FEAT-203',
      title: 'Role-Based Access Control',
      type: 'feature',
      priority: 'critical',
      linkedTests: generateTestLinks(4, ['passed', 'passed', 'passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 4, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'story-3',
      key: 'STORY-303',
      title: 'Admin Role Permissions',
      type: 'story',
      priority: 'critical',
      linkedTests: generateTestLinks(2, ['passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 2, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-5',
      key: 'REQ-405',
      title: 'Super Admin can manage all users',
      type: 'requirement',
      priority: 'critical',
      linkedTests: generateTestLinks(2, ['passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 2, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-6',
      key: 'REQ-406',
      title: 'Regular users cannot access admin panel',
      type: 'requirement',
      priority: 'high',
      linkedTests: [],
      coveragePercentage: 0,
      coverageStatus: 'gap',
      coverageDetail: { passed: 0, failed: 0, blocked: 0, notRun: 0 },
    },
    // Epic 3 - Reporting
    {
      id: 'epic-3',
      key: 'EPIC-103',
      title: 'Analytics & Reporting',
      type: 'epic',
      priority: 'medium',
      linkedTests: generateTestLinks(5, ['passed', 'passed', 'passed', 'not_run', 'not_run']),
      coveragePercentage: 60,
      coverageStatus: 'partial',
      coverageDetail: { passed: 3, failed: 0, blocked: 0, notRun: 2 },
    },
    {
      id: 'feat-4',
      key: 'FEAT-204',
      title: 'Dashboard Widgets',
      type: 'feature',
      priority: 'medium',
      linkedTests: generateTestLinks(3, ['passed', 'passed', 'passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 3, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-7',
      key: 'REQ-407',
      title: 'Real-time data refresh every 30 seconds',
      type: 'requirement',
      priority: 'medium',
      linkedTests: generateTestLinks(1, ['passed']),
      coveragePercentage: 100,
      coverageStatus: 'covered',
      coverageDetail: { passed: 1, failed: 0, blocked: 0, notRun: 0 },
    },
    {
      id: 'req-8',
      key: 'REQ-408',
      title: 'Export reports to PDF format',
      type: 'requirement',
      priority: 'low',
      linkedTests: [],
      coveragePercentage: 0,
      coverageStatus: 'gap',
      coverageDetail: { passed: 0, failed: 0, blocked: 0, notRun: 0 },
    },
  ];

  // Build tree structure
  const tree: RequirementTreeNode[] = [
    {
      id: 'epic-1',
      key: 'EPIC-101',
      type: 'epic',
      title: 'Payment Processing Module',
      coveragePercentage: 87,
      coverageStatus: 'partial',
      hasChildren: true,
      isExpanded: true,
      isSelected: false,
      depth: 0,
      children: [
        {
          id: 'feat-1',
          key: 'FEAT-201',
          type: 'feature',
          title: 'Credit Card Integration',
          coveragePercentage: 100,
          coverageStatus: 'covered',
          hasChildren: true,
          isExpanded: false,
          isSelected: false,
          depth: 1,
          children: [
            {
              id: 'story-1',
              key: 'STORY-301',
              type: 'story',
              title: 'Visa/Mastercard Support',
              coveragePercentage: 100,
              coverageStatus: 'covered',
              hasChildren: true,
              isExpanded: false,
              isSelected: false,
              depth: 2,
              children: [
                {
                  id: 'req-1',
                  key: 'REQ-401',
                  type: 'requirement',
                  title: 'Card number validation',
                  coveragePercentage: 100,
                  coverageStatus: 'covered',
                  hasChildren: false,
                  isExpanded: false,
                  isSelected: false,
                  depth: 3,
                  children: [],
                },
                {
                  id: 'req-2',
                  key: 'REQ-402',
                  type: 'requirement',
                  title: 'CVV encryption',
                  coveragePercentage: 67,
                  coverageStatus: 'partial',
                  hasChildren: false,
                  isExpanded: false,
                  isSelected: false,
                  depth: 3,
                  children: [],
                },
                {
                  id: 'req-3',
                  key: 'REQ-403',
                  type: 'requirement',
                  title: 'Expiry date format',
                  coveragePercentage: 100,
                  coverageStatus: 'covered',
                  hasChildren: false,
                  isExpanded: false,
                  isSelected: false,
                  depth: 3,
                  children: [],
                },
              ],
            },
          ],
        },
        {
          id: 'feat-2',
          key: 'FEAT-202',
          type: 'feature',
          title: 'SADAD Integration',
          coveragePercentage: 50,
          coverageStatus: 'partial',
          hasChildren: true,
          isExpanded: false,
          isSelected: false,
          depth: 1,
          children: [
            {
              id: 'story-2',
              key: 'STORY-302',
              type: 'story',
              title: 'Bill Payment Flow',
              coveragePercentage: 50,
              coverageStatus: 'partial',
              hasChildren: true,
              isExpanded: false,
              isSelected: false,
              depth: 2,
              children: [
                {
                  id: 'req-4',
                  key: 'REQ-404',
                  type: 'requirement',
                  title: 'SADAD OTP verification',
                  coveragePercentage: 0,
                  coverageStatus: 'gap',
                  hasChildren: false,
                  isExpanded: false,
                  isSelected: false,
                  depth: 3,
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'epic-2',
      key: 'EPIC-102',
      type: 'epic',
      title: 'User Management System',
      coveragePercentage: 67,
      coverageStatus: 'partial',
      hasChildren: true,
      isExpanded: false,
      isSelected: false,
      depth: 0,
      children: [
        {
          id: 'feat-3',
          key: 'FEAT-203',
          type: 'feature',
          title: 'Role-Based Access Control',
          coveragePercentage: 100,
          coverageStatus: 'covered',
          hasChildren: true,
          isExpanded: false,
          isSelected: false,
          depth: 1,
          children: [
            {
              id: 'story-3',
              key: 'STORY-303',
              type: 'story',
              title: 'Admin Role Permissions',
              coveragePercentage: 100,
              coverageStatus: 'covered',
              hasChildren: true,
              isExpanded: false,
              isSelected: false,
              depth: 2,
              children: [
                {
                  id: 'req-5',
                  key: 'REQ-405',
                  type: 'requirement',
                  title: 'Super Admin access',
                  coveragePercentage: 100,
                  coverageStatus: 'covered',
                  hasChildren: false,
                  isExpanded: false,
                  isSelected: false,
                  depth: 3,
                  children: [],
                },
                {
                  id: 'req-6',
                  key: 'REQ-406',
                  type: 'requirement',
                  title: 'User restrictions',
                  coveragePercentage: 0,
                  coverageStatus: 'gap',
                  hasChildren: false,
                  isExpanded: false,
                  isSelected: false,
                  depth: 3,
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'epic-3',
      key: 'EPIC-103',
      type: 'epic',
      title: 'Analytics & Reporting',
      coveragePercentage: 60,
      coverageStatus: 'partial',
      hasChildren: true,
      isExpanded: false,
      isSelected: false,
      depth: 0,
      children: [
        {
          id: 'feat-4',
          key: 'FEAT-204',
          type: 'feature',
          title: 'Dashboard Widgets',
          coveragePercentage: 100,
          coverageStatus: 'covered',
          hasChildren: true,
          isExpanded: false,
          isSelected: false,
          depth: 1,
          children: [
            {
              id: 'req-7',
              key: 'REQ-407',
              type: 'requirement',
              title: 'Real-time refresh',
              coveragePercentage: 100,
              coverageStatus: 'covered',
              hasChildren: false,
              isExpanded: false,
              isSelected: false,
              depth: 2,
              children: [],
            },
            {
              id: 'req-8',
              key: 'REQ-408',
              type: 'requirement',
              title: 'PDF export',
              coveragePercentage: 0,
              coverageStatus: 'gap',
              hasChildren: false,
              isExpanded: false,
              isSelected: false,
              depth: 2,
              children: [],
            },
          ],
        },
      ],
    },
  ];

  // Calculate metrics
  const covered = tableData.filter(r => r.coverageStatus === 'covered').length;
  const partial = tableData.filter(r => r.coverageStatus === 'partial').length;
  const gaps = tableData.filter(r => r.coverageStatus === 'gap').length;
  const totalTests = tableData.reduce((sum, r) => sum + r.linkedTests.length, 0);

  const metrics: RTMMetrics = {
    totalRequirements: tableData.length,
    totalTrend: { direction: 'up', value: 4 },
    fullyCovered: covered,
    coveredTrend: { direction: 'up', value: 2 },
    partiallyCovered: partial,
    partialTrend: { direction: 'down', value: 1 },
    coverageGaps: gaps,
    gapsTrend: { direction: 'down', value: 2 },
    linkedTests: totalTests,
    testsTrend: { direction: 'up', value: 8 },
    sparklineData: {
      total: [12, 14, 15, 16, 17, 18, 18],
      covered: [4, 5, 6, 7, 8, 9, 10],
      partial: [5, 5, 5, 5, 5, 5, 5],
      gaps: [3, 4, 4, 4, 4, 4, 3],
      tests: [20, 28, 32, 38, 42, 48, 51],
    },
    overallCoveragePercentage: Math.round((covered + partial * 0.5) / tableData.length * 100),
  };

  return { metrics, tree, tableData };
};
