#!/bin/bash
# One-shot avatar pull: deploy edge function, run puller, stage PNGs.
# Auto-generated by Claude — safe to delete after run.
set -euo pipefail

cd "$(dirname "$0")/.."
echo "▶ Working directory: $(pwd)"

echo ""
echo "━━━ Step 1/3: Deploy jira-avatar-sync Edge Function ━━━"
if ! command -v supabase >/dev/null 2>&1; then
  echo "✗ supabase CLI not found in PATH."
  echo "  Install: brew install supabase/tap/supabase"
  exit 1
fi
supabase functions deploy jira-avatar-sync

echo ""
echo "━━━ Step 2/3: Pull avatars (writes src/assets/avatars/*.png) ━━━"
node scripts/pull-jira-avatars.mjs --force

echo ""
echo "━━━ Step 3/3: Stage PNGs in git ━━━"
git add src/assets/avatars/
echo ""
echo "✓ DONE — staged files:"
git diff --cached --stat -- src/assets/avatars/ | tail -20
echo ""
echo "Review with:  git status"
echo "Commit with:  git commit -m 'feat(avatars): pull canonical faces from Jira'"
