export { KnowledgeBaseCard } from './KnowledgeBaseCard';
export { CreateDocumentDialog } from './CreateDocumentDialog';
export { CreateSpaceDialog } from './CreateSpaceDialog';
export { DocumentVersionHistory } from './DocumentVersionHistory';
export { DocumentTemplates } from './DocumentTemplates';
export { DocumentComments } from './DocumentComments';
export { DocumentLabels } from './DocumentLabels';
export { DocumentAttachments } from './DocumentAttachments';
export { DocumentExport } from './DocumentExport';
export { DocumentWatchers } from './DocumentWatchers';
export { DocumentRestrictions } from './DocumentRestrictions';
export * from './editor';
