import React, { useRef, useEffect } from "react";
import { X, RefreshCw, Copy, Sparkles } from "lucide-react";
import { ChainMetrics } from "@/utils/computeChainMetrics";
import type { AIResult } from "@/utils/generateIntelligence";
import { VerdictSection, ExecutionSection, RiskRadarSection, ChainOfCommandSection } from "./IntelligenceSections";

interface AIStrategyIntelligencePanelProps {
  isOpen: boolean;
  metrics: ChainMetrics | null;
  defects: any[];
  aiResult: AIResult | null;
  isAILoading: boolean;
  onClose: () => void;
  onRegenerate: () => void;
}

export function AIStrategyIntelligencePanel({
  isOpen, metrics, defects, aiResult, isAILoading, onClose, onRegenerate,
}: AIStrategyIntelligencePanelProps) {
  const scrollRef = useRef<HTMLDivElement>(null);

  // Reset scroll position when chain changes
  useEffect(() => {
    if (scrollRef.current && metrics) {
      scrollRef.current.scrollTop = 0;
    }
  }, [metrics?.goalKey]);

  // ESC handler
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    }
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!metrics) return null;

  const chainSubtitle = [
    metrics.themeKey,
    metrics.goalKey,
    `${metrics.krs.length} KRs`,
    metrics.initiativeKey || '⚠ Gap',
    metrics.epicKey || '⚠ Gap',
  ].join(' → ');

  return (
    <div
      className="fixed top-[52px] right-0 bottom-0 z-50 flex flex-col bg-white shadow-2xl border-l border-slate-200"
      style={{
        width: '50vw',
        transform: isOpen ? 'translateX(0)' : 'translateX(100%)',
        transition: 'transform 400ms cubic-bezier(0.16, 1, 0.3, 1)',
      }}
    >
      {/* ═══ Purple AI accent strip ═══ */}
      <div
        className="h-[3px] w-full shrink-0"
        style={{ background: 'linear-gradient(90deg, #7C3AED 0%, #A78BFA 50%, #7C3AED 100%)' }}
      />

      {/* ═══ Panel header ═══ */}
      <div className="px-5 py-4 border-b border-slate-100 shrink-0">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            {/* AI Icon */}
            <div
              className="w-9 h-9 rounded-lg flex items-center justify-center shrink-0"
              style={{ background: 'linear-gradient(135deg, #7C3AED, #6D28D9)' }}
            >
              <Sparkles size={18} className="text-white" />
            </div>
            <div>
              <h2 className="text-[15px] font-[700] text-slate-900 flex items-center gap-2">
                Strategy Intelligence
              </h2>
              <p className="text-[11px] text-slate-400 font-mono mt-0.5 max-w-[400px] truncate">
                {chainSubtitle}
              </p>
            </div>
          </div>
          <button onClick={onClose} className="p-1.5 hover:bg-slate-100 rounded-md transition-colors">
            <X size={18} className="text-slate-400" />
          </button>
        </div>
      </div>

      {/* ═══ Scrollable body — 4 sections ═══ */}
      <div
        ref={scrollRef}
        className="flex-1 overflow-y-auto px-5 py-5"
        style={{ scrollBehavior: 'smooth' }}
      >
        {/* § VERDICT */}
        <VerdictSection metrics={metrics} aiVerdict={aiResult?.verdict || ''} isAILoading={isAILoading} />

        {/* § EXECUTION */}
        <ExecutionSection metrics={metrics} />

        {/* § RISK RADAR */}
        <RiskRadarSection
          metrics={metrics}
          defects={defects}
          riskSignals={aiResult?.riskSignals || []}
          isAILoading={isAILoading}
        />

        {/* § CHAIN OF COMMAND */}
        <ChainOfCommandSection metrics={metrics} />
      </div>

      {/* ═══ Sticky footer ═══ */}
      <div className="px-5 py-3 border-t border-slate-100 flex items-center justify-between shrink-0 bg-white">
        <div className="flex items-center gap-2 text-[11px] text-slate-400">
          <Sparkles size={12} style={{ color: '#7C3AED' }} />
          Generated by AI · {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={onRegenerate}
            disabled={isAILoading}
            className="flex items-center gap-1.5 px-3 py-1.5 text-[12px] font-medium text-white rounded-md transition-colors disabled:opacity-50"
            style={{ background: '#7C3AED' }}
          >
            <RefreshCw size={13} className={isAILoading ? 'animate-spin' : ''} />
            Regenerate
          </button>
          <button
            onClick={() => {
              const text = [aiResult?.verdict, ...(aiResult?.riskSignals || [])].filter(Boolean).join('\n\n');
              navigator.clipboard.writeText(text);
            }}
            className="flex items-center gap-1.5 px-3 py-1.5 text-[12px] font-medium text-slate-600
              hover:text-slate-900 hover:bg-slate-50 rounded-md border border-slate-200 transition-colors"
          >
            <Copy size={13} />
            Copy
          </button>
          <button
            onClick={onClose}
            className="px-3 py-1.5 text-[12px] font-medium text-slate-500 hover:text-slate-700 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

export default AIStrategyIntelligencePanel;
