-- CAT-STRATA-GOVFRAMEWORK-20260719-001 — Slice 3: Perspective revision + Scorecard-model
-- framework provenance/inheritance.
--
-- Two additive concerns, no existing behavior removed:
--   A. strata_create_perspective_draft_version — governed revision of an approved Perspective
--      DEFINITION (clone → draft, preserve lineage, bump version, require reason). Perspective
--      approval remains ordinary governance (generic strata_approve_record); approving a
--      Perspective does NOT make it a framework member.
--   B. Scorecard-model framework provenance: framework_version_id (which framework version a
--      model was seeded from) + per-member weight_source (framework_default | model_override),
--      plus a seeding RPC and a faithful extension of strata_create_model_draft_version so the
--      source framework reference + weight_source survive a model revision.
--
-- Depends on Slices 1–2. Forward-only. NO calc-engine change (out of scope per Plan Lock).

-- ── A. Perspective definition revision ───────────────────────────────────────
CREATE OR REPLACE FUNCTION public.strata_create_perspective_draft_version(
  p_perspective uuid, p_reason text)
RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE v_src public.strata_perspectives%ROWTYPE; v_new uuid; v_open uuid; v_next int;
BEGIN
  IF NOT public.strata_has_role(ARRAY['strategy_office']) THEN
    RAISE EXCEPTION 'creating a perspective version requires the strategy_office or admin role';
  END IF;
  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION 'a change reason is required to create a new perspective version';
  END IF;

  SELECT * INTO v_src FROM public.strata_perspectives WHERE id = p_perspective;
  IF v_src.id IS NULL THEN RAISE EXCEPTION 'perspective not found'; END IF;
  IF v_src.status <> 'approved' THEN
    RAISE EXCEPTION 'new versions are created from the approved perspective (current: %)', v_src.status;
  END IF;

  -- One open successor at a time (draft / pending_approval are the open states).
  SELECT id INTO v_open FROM public.strata_perspectives
   WHERE supersedes_id = p_perspective AND status IN ('draft','pending_approval') LIMIT 1;
  IF v_open IS NOT NULL THEN
    RAISE EXCEPTION 'a draft version of this perspective already exists (%) — finish or discard it first', v_open;
  END IF;

  v_next := GREATEST(
    v_src.version,
    COALESCE((SELECT max(version) FROM public.strata_perspectives WHERE supersedes_id = p_perspective), 0)
  ) + 1;

  -- Clone. slug = NULL → regenerated by trg_strata_perspectives_slug (same convention as
  -- scorecard-model versioning). Deprecated default_weight/order_index copied as-is for
  -- compatibility; they carry no operational meaning (framework weight lives in members).
  INSERT INTO public.strata_perspectives (
    organization_id, name, slug, description, order_index, default_weight, color_token,
    parent_id, version, status, change_reason, supersedes_id
  ) VALUES (
    v_src.organization_id, v_src.name, NULL, v_src.description, v_src.order_index, v_src.default_weight,
    v_src.color_token, v_src.parent_id, v_next, 'draft', btrim(p_reason), p_perspective
  ) RETURNING id INTO v_new;

  INSERT INTO public.strata_audit_events (entity_table, entity_id, action, actor_id, note)
  VALUES ('strata_perspectives', v_new, 'RPC:create_perspective_draft_version', auth.uid(),
          format('v%s draft cloned from v%s (%s): %s', v_next, v_src.version, v_src.name, btrim(p_reason)));
  RETURN v_new;
END;
$$;
GRANT EXECUTE ON FUNCTION public.strata_create_perspective_draft_version(uuid, text) TO authenticated;

-- ── B1. Model framework-provenance columns (nullable; existing rows unaffected) ─
ALTER TABLE public.strata_scorecard_models
  ADD COLUMN IF NOT EXISTS framework_version_id uuid
    REFERENCES public.strata_strategy_framework_versions(id) ON DELETE SET NULL;
COMMENT ON COLUMN public.strata_scorecard_models.framework_version_id IS
  'The strategy framework version this model was seeded from (nullable). Provenance only — a model still owns its own perspective weights independently of the framework.';

ALTER TABLE public.strata_scorecard_model_perspectives
  ADD COLUMN IF NOT EXISTS weight_source text
    CHECK (weight_source IS NULL OR weight_source IN ('framework_default','model_override'));
COMMENT ON COLUMN public.strata_scorecard_model_perspectives.weight_source IS
  'How this member weight was set: framework_default (inherited from the seeding framework version) or model_override (changed on the model). NULL = unknown/legacy (pre-provenance). Zero-assumption: never inferred.';

-- ── B2. Seed a DRAFT model's perspectives from a framework version ───────────
-- Additive path for "start a model from the effective framework". Replaces the draft
-- model's perspective rows with the framework members, marking weight_source=framework_default
-- and recording framework_version_id. Draft/changes_requested only; optimistic concurrency.
CREATE OR REPLACE FUNCTION public.strata_seed_model_perspectives_from_framework(
  p_model uuid, p_framework_version uuid, p_expected_updated_at timestamptz DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE m public.strata_scorecard_models%ROWTYPE; v_fstatus text;
BEGIN
  IF NOT public.strata_has_role(ARRAY['strategy_office']) THEN
    RAISE EXCEPTION 'seeding model perspectives requires the strategy_office or admin role';
  END IF;
  SELECT * INTO m FROM public.strata_scorecard_models WHERE id = p_model FOR UPDATE;
  IF m.id IS NULL THEN RAISE EXCEPTION 'scorecard model not found'; END IF;
  IF m.status NOT IN ('draft','changes_requested') THEN
    RAISE EXCEPTION 'perspectives can only be seeded on a draft or changes-requested model (current: %)', m.status;
  END IF;
  IF m.created_by IS DISTINCT FROM auth.uid() AND NOT public.strata_is_admin() THEN
    RAISE EXCEPTION 'only the model author (or an admin) may seed its perspectives';
  END IF;
  IF p_expected_updated_at IS NOT NULL AND m.updated_at <> p_expected_updated_at THEN
    RAISE EXCEPTION 'this model changed after you opened it — refresh, then try again';
  END IF;

  SELECT status INTO v_fstatus FROM public.strata_strategy_framework_versions WHERE id = p_framework_version;
  IF v_fstatus IS NULL THEN RAISE EXCEPTION 'framework version not found'; END IF;
  IF v_fstatus <> 'approved' THEN
    RAISE EXCEPTION 'a model can only inherit from an approved framework version (current: %)', v_fstatus;
  END IF;

  DELETE FROM public.strata_scorecard_model_perspectives WHERE model_id = p_model;
  INSERT INTO public.strata_scorecard_model_perspectives (model_id, perspective_id, weight, order_index, weight_source)
  SELECT p_model, perspective_id, weight, order_index, 'framework_default'
    FROM public.strata_strategy_framework_members WHERE framework_version_id = p_framework_version;

  UPDATE public.strata_scorecard_models SET framework_version_id = p_framework_version, updated_at = now() WHERE id = p_model;

  INSERT INTO public.strata_audit_events (entity_table, entity_id, action, actor_id, note)
  VALUES ('strata_scorecard_models', p_model, 'RPC:seed_model_perspectives_from_framework', auth.uid(),
          format('seeded model perspectives from framework version %s', p_framework_version));
END;
$$;
GRANT EXECUTE ON FUNCTION public.strata_seed_model_perspectives_from_framework(uuid, uuid, timestamptz) TO authenticated;

-- ── B3. Faithful extension of strata_create_model_draft_version ──────────────
-- Reproduces the current body (20260718200000 §13) VERBATIM, adding ONLY: copy
-- framework_version_id to the new version, and copy weight_source per perspective. All
-- existing behavior (role gate, reason gate, editable/approved-source rules, one-open
-- successor, monotonic version, measures copy, audit) is preserved unchanged.
CREATE OR REPLACE FUNCTION public.strata_create_model_draft_version(
  p_model  uuid,
  p_reason text
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_src  public.strata_scorecard_models%ROWTYPE;
  v_new  uuid;
  v_open uuid;
  v_next int;
BEGIN
  IF NOT public.strata_has_role(ARRAY['strategy_office']) THEN
    RAISE EXCEPTION 'creating a scorecard model version requires the strategy_office or admin role';
  END IF;

  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION 'a change reason is required to create a new version';
  END IF;

  SELECT * INTO v_src FROM public.strata_scorecard_models WHERE id = p_model;
  IF v_src.id IS NULL THEN
    RAISE EXCEPTION 'scorecard model not found';
  END IF;

  IF v_src.status IN ('draft','changes_requested') THEN
    RAISE EXCEPTION 'this version is already editable (%) — edit it directly instead of creating a version', v_src.status;
  END IF;

  IF v_src.status <> 'approved' THEN
    RAISE EXCEPTION 'new versions are created from the approved version (current: %)', v_src.status;
  END IF;

  SELECT id INTO v_open
    FROM public.strata_scorecard_models
   WHERE supersedes_id = p_model AND status IN ('draft','pending_approval','changes_requested')
   LIMIT 1;
  IF v_open IS NOT NULL THEN
    RAISE EXCEPTION 'a draft version of this model already exists (%) — finish or discard it first', v_open;
  END IF;

  v_next := GREATEST(
    v_src.version,
    COALESCE((SELECT max(version) FROM public.strata_scorecard_models WHERE supersedes_id = p_model), 0)
  ) + 1;

  INSERT INTO public.strata_scorecard_models (
    organization_id, name, slug, description, owner_scope_type, rollup_method,
    threshold_scheme_id, period_granularity, version, status,
    effective_from, effective_to, approved_by, approved_at, change_reason, supersedes_id,
    framework_version_id
  ) VALUES (
    v_src.organization_id, v_src.name, NULL, v_src.description, v_src.owner_scope_type,
    v_src.rollup_method, v_src.threshold_scheme_id, v_src.period_granularity,
    v_next, 'draft',
    NULL, NULL, NULL, NULL, p_reason, p_model,
    v_src.framework_version_id
  ) RETURNING id INTO v_new;

  INSERT INTO public.strata_scorecard_model_perspectives (model_id, perspective_id, weight, order_index, weight_source)
  SELECT v_new, perspective_id, weight, order_index, weight_source
    FROM public.strata_scorecard_model_perspectives
   WHERE model_id = p_model;

  INSERT INTO public.strata_scorecard_model_measures (
    model_id, perspective_id, kpi_id, weight, order_index, required, aggregation_method, target_policy)
  SELECT v_new, perspective_id, kpi_id, weight, order_index, required, aggregation_method, target_policy
    FROM public.strata_scorecard_model_measures
   WHERE model_id = p_model;

  INSERT INTO public.strata_audit_events (entity_table, entity_id, action, actor_id, note)
  VALUES ('strata_scorecard_models', v_new, 'RPC:create_model_draft_version', auth.uid(),
          format('v%s draft cloned from v%s (%s): %s',
                 v_next, v_src.version, v_src.name, p_reason));

  RETURN v_new;
END;
$function$;

-- ── B4. Extend framework dependency-impact to include model inheritance ──────
-- Now that models can reference a framework version, report models seeded from a version.
CREATE OR REPLACE FUNCTION public.strata_framework_dependency_impact(p_version uuid)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE v_member_count int; v_element_count int; v_model_count int;
BEGIN
  SELECT COUNT(*) INTO v_member_count FROM public.strata_strategy_framework_members WHERE framework_version_id = p_version;
  SELECT COUNT(*) INTO v_element_count
    FROM public.strata_strategy_elements e
   WHERE e.perspective_id IN (SELECT perspective_id FROM public.strata_strategy_framework_members WHERE framework_version_id = p_version);
  SELECT COUNT(*) INTO v_model_count FROM public.strata_scorecard_models WHERE framework_version_id = p_version;
  RETURN jsonb_build_object(
    'version_id', p_version,
    'member_count', v_member_count,
    'strategy_elements_using_member_perspectives', v_element_count,
    'scorecard_models_seeded_from_version', v_model_count
  );
END;
$$;
