// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Publishable (anon) credentials for project lmqwtldpfacrrlvdnmld. These are
// client-safe by design (they ship in the browser bundle) and are the same
// values already documented in CLAUDE.md. They serve as a fallback so the app
// always boots even when VITE_SUPABASE_* env vars are absent (fresh container,
// web preview, or a dev server started before .env existed). Env vars, when
// present, always take precedence.
// In dev, a missing env var must never silently retarget the PRODUCTION
// project (real risk: local sessions writing to prod data).
if (import.meta.env.DEV && !import.meta.env.VITE_SUPABASE_URL) {
  throw new Error(
    'VITE_SUPABASE_URL is not set — refusing to fall back to the production ' +
      'Supabase project in dev. Add VITE_SUPABASE_URL to .env.local.',
  );
}
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL || 'https://lmqwtldpfacrrlvdnmld.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtcXd0bGRwZmFjcnJsdmRubWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg4NTkwODEsImV4cCI6MjA5NDQzNTA4MX0.CITWnsiEJEd1B-G4RReYZdaTFbBNvw8NnM8OrRvDX8s';

// Import the supabase client like this:
// import { supabase, typedQuery } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'catalyst-auth-token',
    detectSessionInUrl: true,
  }
});

/**
 * Typed query helper — use instead of `(supabase as any).from('table')`.
 * Provides the same API but avoids the `as any` cast scattered across 855 call sites.
 *
 * Usage:
 *   import { supabase, typedQuery } from "@/integrations/supabase/client";
 *   const { data } = await typedQuery('my_custom_table').select('*').eq('id', id);
 *
 * This is a migration bridge until `supabase gen types` is re-run to include
 * all custom tables in the Database type.
 */
export function typedQuery(table: string) {
  return (supabase as any).from(table);
}

/**
 * Typed RPC helper — use instead of `(supabase as any).rpc('fn_name', params)`.
 */
export function typedRpc(fnName: string, params?: Record<string, unknown>) {
  return (supabase as any).rpc(fnName, params);
}