// Test Module Hooks Exports
export { useProjectScope } from './useProjectScope';
export { useTestKPIs, useTestQuickStats } from './useTestKPIs';
export { useTestCases, useTestCase } from './useTestCases';
export { useTestCycles, useTestCycle } from './useTestCycles';
export { useExecutions, useExecution, useCycleExecutionStats } from './useExecutions';
export { useTestSets, useTestSet } from './useTestSets';
export { useCycleExecution } from './useCycleExecution';
export { useTestReports, useTestReport } from './useTestReports';
export { useUserActivityReport, useActivityDrillDown, useLogTestActivity } from './useUserActivity';
export type { UserActivityReportState, ActivityAggregate, ActivityItem, ActivityType, TimeGrouping } from './useUserActivity';
export { useTestDashboards, useReportSchedule } from './useTestDashboards';
export type { GadgetType, GadgetPosition, GadgetConfig, DashboardGadget, Dashboard, CreateDashboardInput, CreateGadgetInput, UpdateGadgetInput } from './useTestDashboards';
export { useTraceabilityMatrix } from './useTraceabilityMatrix';
export type { TraceabilityMatrixData, TraceabilityChain, CoverageGap, TraceabilityRequirement, TraceabilityTestCase, TraceabilityExecution, TraceabilityDefect } from './useTraceabilityMatrix';
export { useTestAdminConfig } from './useTestAdminConfig';
export type { TestCaseType, TestCaseStatus, TestCasePriority, TestRunStatus, TestFieldConfig, TestAdminSetting } from './useTestAdminConfig';
export { useNotificationPreferences, useTestNotifications, useCreateNotification } from './useTestNotifications';
export { useGenerateTestCases, useAnalyzeCoverageGaps, useFailureClusters, useCycleRiskPrediction, useAIDrafts, useAIAuditLog } from './useTestAI';
export { useLogActivity, useEntityActivityTimeline, useProgramActivityTimeline, useGovernanceStats } from './useTestGovernance';
